#!/usr/local/bin/perl

# $Header$

# Script used to 'groom' the distribution for release after doing the 'cvs export'.
# (Although not really needed in the distribution, this is bundled for
# completeness and for 'disaster-recovery' purposes.)

@files = <*>;
open(COPY, "<COPYRIGHT");
@copy=<COPY>;
close(COPY);
for $f (@files) {
    print "doing $f\n";
    rename "$f","$f.tmp";
    open (IN, "<$f.tmp");
    open (OUT, ">$f");
    while (<IN>) {
	if (m,\/\* COPYRIGHT \*\/,) {
	    print OUT "/**********************************************************************\n";
	    for (@copy) {
		print OUT " * ".$_;
	    }
	    print OUT " *********************************************************************/\n";
	} elsif (m,\# COPYRIGHT,) {
	    print OUT "#\n";
	    for (@copy) {
		print OUT "# ".$_;
	    }
	    print OUT "#\n";
	} else {
	    print OUT;
	}
    }
    close(IN);
    close(OUT);
    unlink "$f.tmp";
}
