/***************************************
  $Header$

  Table of all cmavo, indexed by hash function computed in lex1.c.
  Most of this file was autogenerated by a perl script.
  ***************************************/

/* COPYRIGHT */

#include "cmavotab.h"
#include "rpc.tab.h"
#define UNKNOWN 0

CmavoCell cmavo_table[] = {
  { "01085 Lojb", UNKNOWN, "LogFlash cmavo list 06/13/94        010" }, /* 0 */
  { "", UNKNOWN, "" }, /* 1 */
  { "", UNKNOWN, "" }, /* 2 */
  { "", UNKNOWN, "" }, /* 3 */
  { "", UNKNOWN, "" }, /* 4 */
  { "", UNKNOWN, "" }, /* 5 */
  { "", UNKNOWN, "" }, /* 6 */
  { "", UNKNOWN, "" }, /* 7 */
  { "", UNKNOWN, "" }, /* 8 */
  { "", UNKNOWN, "" }, /* 9 */
  { "", UNKNOWN, "" }, /* 10 */
  { "", UNKNOWN, "" }, /* 11 */
  { "", UNKNOWN, "" }, /* 12 */
  { "", UNKNOWN, "" }, /* 13 */
  { "a", A, "sumti or" }, /* 14 */
  { "", UNKNOWN, "" }, /* 15 */
  { "", UNKNOWN, "" }, /* 16 */
  { "ai", UI, "intent" }, /* 17 */
  { "", UNKNOWN, "" }, /* 18 */
  { "au", UI, "desire" }, /* 19 */
  { "", UNKNOWN, "" }, /* 20 */
  { "", UNKNOWN, "" }, /* 21 */
  { "a\'a", UI, "attentive" }, /* 22 */
  { "a\'e", UI, "alertness" }, /* 23 */
  { "a\'i", UI, "effort" }, /* 24 */
  { "a\'o", UI, "hope" }, /* 25 */
  { "a\'u", UI, "interest" }, /* 26 */
  { "", UNKNOWN, "" }, /* 27 */
  { "e", A, "sumti and" }, /* 28 */
  { "", UNKNOWN, "" }, /* 29 */
  { "", UNKNOWN, "" }, /* 30 */
  { "ei", UI, "obligation" }, /* 31 */
  { "", UNKNOWN, "" }, /* 32 */
  { "", UNKNOWN, "" }, /* 33 */
  { "", UNKNOWN, "" }, /* 34 */
  { "", UNKNOWN, "" }, /* 35 */
  { "e\'a", UI, "permission" }, /* 36 */
  { "e\'e", UI, "competence" }, /* 37 */
  { "e\'i", UI, "constraint" }, /* 38 */
  { "e\'o", UI, "request" }, /* 39 */
  { "e\'u", UI, "suggestion" }, /* 40 */
  { "", UNKNOWN, "" }, /* 41 */
  { "i", I, "sentence link" }, /* 42 */
  { "ia", UI, "belief" }, /* 43 */
  { "ie", UI, "agreement" }, /* 44 */
  { "ii", UI, "fear" }, /* 45 */
  { "io", UI, "respect" }, /* 46 */
  { "iu", UI, "love" }, /* 47 */
  { "", UNKNOWN, "" }, /* 48 */
  { "", UNKNOWN, "" }, /* 49 */
  { "i\'a", UI, "acceptance" }, /* 50 */
  { "i\'e", UI, "approval" }, /* 51 */
  { "i\'i", UI, "togetherness" }, /* 52 */
  { "i\'o", UI, "appreciation" }, /* 53 */
  { "i\'u", UI, "familiarity" }, /* 54 */
  { "", UNKNOWN, "" }, /* 55 */
  { "o", A, "sumti iff" }, /* 56 */
  { "", UNKNOWN, "" }, /* 57 */
  { "", UNKNOWN, "" }, /* 58 */
  { "oi", UI, "complaint" }, /* 59 */
  { "", UNKNOWN, "" }, /* 60 */
  { "", UNKNOWN, "" }, /* 61 */
  { "", UNKNOWN, "" }, /* 62 */
  { "", UNKNOWN, "" }, /* 63 */
  { "o\'a", UI, "pride" }, /* 64 */
  { "o\'e", UI, "closeness" }, /* 65 */
  { "o\'i", UI, "caution" }, /* 66 */
  { "o\'o", UI, "patience" }, /* 67 */
  { "o\'u", UI, "relaxation" }, /* 68 */
  { "", UNKNOWN, "" }, /* 69 */
  { "u", A, "sumti whether" }, /* 70 */
  { "ua", UI, "discovery" }, /* 71 */
  { "ue", UI, "surprise" }, /* 72 */
  { "ui", UI, "happiness" }, /* 73 */
  { "uo", UI, "completion" }, /* 74 */
  { "uu", UI, "pity" }, /* 75 */
  { "", UNKNOWN, "" }, /* 76 */
  { "", UNKNOWN, "" }, /* 77 */
  { "u\'a", UI, "gain" }, /* 78 */
  { "u\'e", UI, "wonder" }, /* 79 */
  { "u\'i", UI, "amusement" }, /* 80 */
  { "u\'o", UI, "courage" }, /* 81 */
  { "u\'u", UI, "repentance" }, /* 82 */
  { "", UNKNOWN, "" }, /* 83 */
  { "y", Y, "hesitation" }, /* 84 */
  { "", UNKNOWN, "" }, /* 85 */
  { "", UNKNOWN, "" }, /* 86 */
  { "", UNKNOWN, "" }, /* 87 */
  { "", UNKNOWN, "" }, /* 88 */
  { "", UNKNOWN, "" }, /* 89 */
  { "", UNKNOWN, "" }, /* 90 */
  { "", UNKNOWN, "" }, /* 91 */
  { "", UNKNOWN, "" }, /* 92 */
  { "", UNKNOWN, "" }, /* 93 */
  { "", UNKNOWN, "" }, /* 94 */
  { "", UNKNOWN, "" }, /* 95 */
  { "", UNKNOWN, "" }, /* 96 */
  { "y\'y", BY, "'" }, /* 97 */
  { "", UNKNOWN, "" }, /* 98 */
  { "", UNKNOWN, "" }, /* 99 */
  { "", UNKNOWN, "" }, /* 100 */
  { "", UNKNOWN, "" }, /* 101 */
  { "", UNKNOWN, "" }, /* 102 */
  { "", UNKNOWN, "" }, /* 103 */
  { "", UNKNOWN, "" }, /* 104 */
  { "", UNKNOWN, "" }, /* 105 */
  { "", UNKNOWN, "" }, /* 106 */
  { "", UNKNOWN, "" }, /* 107 */
  { "", UNKNOWN, "" }, /* 108 */
  { "", UNKNOWN, "" }, /* 109 */
  { "", UNKNOWN, "" }, /* 110 */
  { "", UNKNOWN, "" }, /* 111 */
  { "ba", PU, "after" }, /* 112 */
  { "", UNKNOWN, "" }, /* 113 */
  { "", UNKNOWN, "" }, /* 114 */
  { "bai", BAI, "compelled by" }, /* 115 */
  { "", UNKNOWN, "" }, /* 116 */
  { "bau", BAI, "in language" }, /* 117 */
  { "", UNKNOWN, "" }, /* 118 */
  { "", UNKNOWN, "" }, /* 119 */
  { "ba\'a", UI, "I anticipate" }, /* 120 */
  { "ba\'e", BAhE, "emphasize next" }, /* 121 */
  { "ba\'i", BAI, "replaced by" }, /* 122 */
  { "ba\'o", ZAhO, "perfective" }, /* 123 */
  { "ba\'u", UI, "exaggeration" }, /* 124 */
  { "", UNKNOWN, "" }, /* 125 */
  { "be", BE, "link sumti" }, /* 126 */
  { "", UNKNOWN, "" }, /* 127 */
  { "", UNKNOWN, "" }, /* 128 */
  { "bei", BEI, "link more sumti" }, /* 129 */
  { "", UNKNOWN, "" }, /* 130 */
  { "", UNKNOWN, "" }, /* 131 */
  { "", UNKNOWN, "" }, /* 132 */
  { "", UNKNOWN, "" }, /* 133 */
  { "be\'a", FAhA, "north of" }, /* 134 */
  { "be\'e", COI, "request to send" }, /* 135 */
  { "be\'i", BAI, "sent by" }, /* 136 */
  { "be\'o", BEhO, "end linked sumti" }, /* 137 */
  { "be\'u", UI, "lack" }, /* 138 */
  { "", UNKNOWN, "" }, /* 139 */
  { "bi", PA, "8" }, /* 140 */
  { "", UNKNOWN, "" }, /* 141 */
  { "", UNKNOWN, "" }, /* 142 */
  { "", UNKNOWN, "" }, /* 143 */
  { "", UNKNOWN, "" }, /* 144 */
  { "", UNKNOWN, "" }, /* 145 */
  { "", UNKNOWN, "" }, /* 146 */
  { "", UNKNOWN, "" }, /* 147 */
  { "", UNKNOWN, "" }, /* 148 */
  { "", UNKNOWN, "" }, /* 149 */
  { "bi\'i", BIhI, "unordered interval" }, /* 150 */
  { "bi\'o", BIhI, "ordered interval" }, /* 151 */
  { "bi\'u", UI, "new information" }, /* 152 */
  { "", UNKNOWN, "" }, /* 153 */
  { "bo", BO, "short scope link" }, /* 154 */
  { "", UNKNOWN, "" }, /* 155 */
  { "", UNKNOWN, "" }, /* 156 */
  { "boi", BOI, "end number or lerfu" }, /* 157 */
  { "", UNKNOWN, "" }, /* 158 */
  { "", UNKNOWN, "" }, /* 159 */
  { "", UNKNOWN, "" }, /* 160 */
  { "", UNKNOWN, "" }, /* 161 */
  { "", UNKNOWN, "" }, /* 162 */
  { "", UNKNOWN, "" }, /* 163 */
  { "", UNKNOWN, "" }, /* 164 */
  { "", UNKNOWN, "" }, /* 165 */
  { "", UNKNOWN, "" }, /* 166 */
  { "", UNKNOWN, "" }, /* 167 */
  { "bu", BU, "word to lerfu" }, /* 168 */
  { "", UNKNOWN, "" }, /* 169 */
  { "", UNKNOWN, "" }, /* 170 */
  { "", UNKNOWN, "" }, /* 171 */
  { "", UNKNOWN, "" }, /* 172 */
  { "", UNKNOWN, "" }, /* 173 */
  { "", UNKNOWN, "" }, /* 174 */
  { "", UNKNOWN, "" }, /* 175 */
  { "bu\'a", GOhA, "some selbri 1" }, /* 176 */
  { "bu\'e", GOhA, "some selbri 2" }, /* 177 */
  { "bu\'i", GOhA, "some selbri 3" }, /* 178 */
  { "bu\'o", UI, "start emotion" }, /* 179 */
  { "bu\'u", FAhA, "coincident with" }, /* 180 */
  { "", UNKNOWN, "" }, /* 181 */
  { "by", BY, "b" }, /* 182 */
  { "", UNKNOWN, "" }, /* 183 */
  { "", UNKNOWN, "" }, /* 184 */
  { "", UNKNOWN, "" }, /* 185 */
  { "", UNKNOWN, "" }, /* 186 */
  { "", UNKNOWN, "" }, /* 187 */
  { "", UNKNOWN, "" }, /* 188 */
  { "", UNKNOWN, "" }, /* 189 */
  { "", UNKNOWN, "" }, /* 190 */
  { "", UNKNOWN, "" }, /* 191 */
  { "", UNKNOWN, "" }, /* 192 */
  { "", UNKNOWN, "" }, /* 193 */
  { "", UNKNOWN, "" }, /* 194 */
  { "", UNKNOWN, "" }, /* 195 */
  { "", UNKNOWN, "" }, /* 196 */
  { "", UNKNOWN, "" }, /* 197 */
  { "", UNKNOWN, "" }, /* 198 */
  { "", UNKNOWN, "" }, /* 199 */
  { "", UNKNOWN, "" }, /* 200 */
  { "", UNKNOWN, "" }, /* 201 */
  { "", UNKNOWN, "" }, /* 202 */
  { "", UNKNOWN, "" }, /* 203 */
  { "", UNKNOWN, "" }, /* 204 */
  { "", UNKNOWN, "" }, /* 205 */
  { "", UNKNOWN, "" }, /* 206 */
  { "", UNKNOWN, "" }, /* 207 */
  { "", UNKNOWN, "" }, /* 208 */
  { "", UNKNOWN, "" }, /* 209 */
  { "ca", PU, "during" }, /* 210 */
  { "", UNKNOWN, "" }, /* 211 */
  { "", UNKNOWN, "" }, /* 212 */
  { "cai", CAI, "intense emotion" }, /* 213 */
  { "", UNKNOWN, "" }, /* 214 */
  { "cau", BAI, "lacked by" }, /* 215 */
  { "", UNKNOWN, "" }, /* 216 */
  { "", UNKNOWN, "" }, /* 217 */
  { "ca\'a", CAhA, "actually is" }, /* 218 */
  { "ca\'e", UI, "I define" }, /* 219 */
  { "ca\'i", BAI, "by authority of" }, /* 220 */
  { "ca\'o", ZAhO, "continuative" }, /* 221 */
  { "ca\'u", FAhA, "in front of" }, /* 222 */
  { "", UNKNOWN, "" }, /* 223 */
  { "ce", JOI, "in a set with" }, /* 224 */
  { "", UNKNOWN, "" }, /* 225 */
  { "", UNKNOWN, "" }, /* 226 */
  { "cei", CEI, "pro-bridi assign" }, /* 227 */
  { "", UNKNOWN, "" }, /* 228 */
  { "", UNKNOWN, "" }, /* 229 */
  { "", UNKNOWN, "" }, /* 230 */
  { "", UNKNOWN, "" }, /* 231 */
  { "ce\'a", LAU, "font shift" }, /* 232 */
  { "", UNKNOWN, "" }, /* 233 */
  { "ce\'i", PA, "percent" }, /* 234 */
  { "ce\'o", JOI, "in a sequence with" }, /* 235 */
  { "", UNKNOWN, "" }, /* 236 */
  { "", UNKNOWN, "" }, /* 237 */
  { "ci", PA, "3" }, /* 238 */
  { "", UNKNOWN, "" }, /* 239 */
  { "", UNKNOWN, "" }, /* 240 */
  { "", UNKNOWN, "" }, /* 241 */
  { "", UNKNOWN, "" }, /* 242 */
  { "", UNKNOWN, "" }, /* 243 */
  { "", UNKNOWN, "" }, /* 244 */
  { "", UNKNOWN, "" }, /* 245 */
  { "", UNKNOWN, "" }, /* 246 */
  { "ci\'e", BAI, "in system" }, /* 247 */
  { "ci\'i", PA, "infinity" }, /* 248 */
  { "ci\'o", BAI, "emotionally felt by" }, /* 249 */
  { "ci\'u", BAI, "on the scale" }, /* 250 */
  { "", UNKNOWN, "" }, /* 251 */
  { "co", CO, "tanru inversion" }, /* 252 */
  { "", UNKNOWN, "" }, /* 253 */
  { "", UNKNOWN, "" }, /* 254 */
  { "coi", COI, "greetings" }, /* 255 */
  { "", UNKNOWN, "" }, /* 256 */
  { "", UNKNOWN, "" }, /* 257 */
  { "", UNKNOWN, "" }, /* 258 */
  { "", UNKNOWN, "" }, /* 259 */
  { "co\'a", ZAhO, "initiative" }, /* 260 */
  { "co\'e", GOhA, "unspecif bridi" }, /* 261 */
  { "co\'i", ZAhO, "achievative" }, /* 262 */
  { "co\'o", COI, "partings" }, /* 263 */
  { "co\'u", ZAhO, "cessative" }, /* 264 */
  { "", UNKNOWN, "" }, /* 265 */
  { "cu", CU, "selbri separator" }, /* 266 */
  { "", UNKNOWN, "" }, /* 267 */
  { "", UNKNOWN, "" }, /* 268 */
  { "", UNKNOWN, "" }, /* 269 */
  { "", UNKNOWN, "" }, /* 270 */
  { "", UNKNOWN, "" }, /* 271 */
  { "", UNKNOWN, "" }, /* 272 */
  { "", UNKNOWN, "" }, /* 273 */
  { "cu\'a", VUhU, "absolute value" }, /* 274 */
  { "cu\'e", CUhE, "modal ?" }, /* 275 */
  { "cu\'i", CAI, "neutral emotion" }, /* 276 */
  { "cu\'o", MOI, "probability selbri" }, /* 277 */
  { "cu\'u", BAI, "as said by" }, /* 278 */
  { "", UNKNOWN, "" }, /* 279 */
  { "cy", BY, "c" }, /* 280 */
  { "", UNKNOWN, "" }, /* 281 */
  { "", UNKNOWN, "" }, /* 282 */
  { "", UNKNOWN, "" }, /* 283 */
  { "", UNKNOWN, "" }, /* 284 */
  { "", UNKNOWN, "" }, /* 285 */
  { "", UNKNOWN, "" }, /* 286 */
  { "", UNKNOWN, "" }, /* 287 */
  { "", UNKNOWN, "" }, /* 288 */
  { "", UNKNOWN, "" }, /* 289 */
  { "", UNKNOWN, "" }, /* 290 */
  { "", UNKNOWN, "" }, /* 291 */
  { "", UNKNOWN, "" }, /* 292 */
  { "", UNKNOWN, "" }, /* 293 */
  { "", UNKNOWN, "" }, /* 294 */
  { "", UNKNOWN, "" }, /* 295 */
  { "", UNKNOWN, "" }, /* 296 */
  { "", UNKNOWN, "" }, /* 297 */
  { "", UNKNOWN, "" }, /* 298 */
  { "", UNKNOWN, "" }, /* 299 */
  { "", UNKNOWN, "" }, /* 300 */
  { "", UNKNOWN, "" }, /* 301 */
  { "", UNKNOWN, "" }, /* 302 */
  { "", UNKNOWN, "" }, /* 303 */
  { "", UNKNOWN, "" }, /* 304 */
  { "", UNKNOWN, "" }, /* 305 */
  { "", UNKNOWN, "" }, /* 306 */
  { "", UNKNOWN, "" }, /* 307 */
  { "da", KOhA, "something 1" }, /* 308 */
  { "", UNKNOWN, "" }, /* 309 */
  { "", UNKNOWN, "" }, /* 310 */
  { "dai", UI, "empathy" }, /* 311 */
  { "", UNKNOWN, "" }, /* 312 */
  { "dau", PA, "hex digit A" }, /* 313 */
  { "", UNKNOWN, "" }, /* 314 */
  { "", UNKNOWN, "" }, /* 315 */
  { "da\'a", PA, "all except" }, /* 316 */
  { "da\'e", KOhA, "eventual utterance" }, /* 317 */
  { "da\'i", UI, "supposing" }, /* 318 */
  { "da\'o", DAhO, "cancel pro-assigns" }, /* 319 */
  { "da\'u", KOhA, "earlier utterance" }, /* 320 */
  { "", UNKNOWN, "" }, /* 321 */
  { "de", KOhA, "something 2" }, /* 322 */
  { "", UNKNOWN, "" }, /* 323 */
  { "", UNKNOWN, "" }, /* 324 */
  { "dei", KOhA, "this utterance" }, /* 325 */
  { "", UNKNOWN, "" }, /* 326 */
  { "", UNKNOWN, "" }, /* 327 */
  { "", UNKNOWN, "" }, /* 328 */
  { "", UNKNOWN, "" }, /* 329 */
  { "de\'a", ZAhO, "pausative" }, /* 330 */
  { "de\'e", KOhA, "soon utterance" }, /* 331 */
  { "de\'i", BAI, "dated" }, /* 332 */
  { "de\'o", VUhU, "logarithm" }, /* 333 */
  { "de\'u", KOhA, "recent utterance" }, /* 334 */
  { "", UNKNOWN, "" }, /* 335 */
  { "di", KOhA, "something 3" }, /* 336 */
  { "", UNKNOWN, "" }, /* 337 */
  { "", UNKNOWN, "" }, /* 338 */
  { "", UNKNOWN, "" }, /* 339 */
  { "", UNKNOWN, "" }, /* 340 */
  { "", UNKNOWN, "" }, /* 341 */
  { "", UNKNOWN, "" }, /* 342 */
  { "", UNKNOWN, "" }, /* 343 */
  { "di\'a", ZAhO, "resumptitive" }, /* 344 */
  { "di\'e", KOhA, "next utterance" }, /* 345 */
  { "di\'i", TAhE, "regularly" }, /* 346 */
  { "di\'o", BAI, "at the locus of" }, /* 347 */
  { "di\'u", KOhA, "last utterance" }, /* 348 */
  { "", UNKNOWN, "" }, /* 349 */
  { "do", KOhA, "you" }, /* 350 */
  { "", UNKNOWN, "" }, /* 351 */
  { "", UNKNOWN, "" }, /* 352 */
  { "doi", DOI, "vocative marker" }, /* 353 */
  { "", UNKNOWN, "" }, /* 354 */
  { "", UNKNOWN, "" }, /* 355 */
  { "", UNKNOWN, "" }, /* 356 */
  { "", UNKNOWN, "" }, /* 357 */
  { "do\'a", UI, "generously" }, /* 358 */
  { "do\'e", BAI, "unspecif modal" }, /* 359 */
  { "do\'i", KOhA, "unspecif utterance" }, /* 360 */
  { "do\'o", KOhA, "you and others" }, /* 361 */
  { "do\'u", DOhU, "end vocative" }, /* 362 */
  { "", UNKNOWN, "" }, /* 363 */
  { "du", GOhA, "same identity as" }, /* 364 */
  { "", UNKNOWN, "" }, /* 365 */
  { "", UNKNOWN, "" }, /* 366 */
  { "", UNKNOWN, "" }, /* 367 */
  { "", UNKNOWN, "" }, /* 368 */
  { "", UNKNOWN, "" }, /* 369 */
  { "", UNKNOWN, "" }, /* 370 */
  { "", UNKNOWN, "" }, /* 371 */
  { "du\'a", FAhA, "east of" }, /* 372 */
  { "du\'e", PA, "too many" }, /* 373 */
  { "du\'i", BAI, "as much as" }, /* 374 */
  { "du\'o", BAI, "according to" }, /* 375 */
  { "du\'u", NU, "bridi abstract" }, /* 376 */
  { "", UNKNOWN, "" }, /* 377 */
  { "dy", BY, "d" }, /* 378 */
  { "", UNKNOWN, "" }, /* 379 */
  { "", UNKNOWN, "" }, /* 380 */
  { "", UNKNOWN, "" }, /* 381 */
  { "", UNKNOWN, "" }, /* 382 */
  { "", UNKNOWN, "" }, /* 383 */
  { "", UNKNOWN, "" }, /* 384 */
  { "", UNKNOWN, "" }, /* 385 */
  { "", UNKNOWN, "" }, /* 386 */
  { "", UNKNOWN, "" }, /* 387 */
  { "", UNKNOWN, "" }, /* 388 */
  { "", UNKNOWN, "" }, /* 389 */
  { "", UNKNOWN, "" }, /* 390 */
  { "", UNKNOWN, "" }, /* 391 */
  { "", UNKNOWN, "" }, /* 392 */
  { "", UNKNOWN, "" }, /* 393 */
  { "", UNKNOWN, "" }, /* 394 */
  { "", UNKNOWN, "" }, /* 395 */
  { "", UNKNOWN, "" }, /* 396 */
  { "", UNKNOWN, "" }, /* 397 */
  { "", UNKNOWN, "" }, /* 398 */
  { "", UNKNOWN, "" }, /* 399 */
  { "", UNKNOWN, "" }, /* 400 */
  { "", UNKNOWN, "" }, /* 401 */
  { "", UNKNOWN, "" }, /* 402 */
  { "", UNKNOWN, "" }, /* 403 */
  { "", UNKNOWN, "" }, /* 404 */
  { "", UNKNOWN, "" }, /* 405 */
  { "fa", FA, "1st sumti place" }, /* 406 */
  { "", UNKNOWN, "" }, /* 407 */
  { "", UNKNOWN, "" }, /* 408 */
  { "fai", FA, "extra sumti place" }, /* 409 */
  { "", UNKNOWN, "" }, /* 410 */
  { "fau", BAI, "in the event of" }, /* 411 */
  { "", UNKNOWN, "" }, /* 412 */
  { "", UNKNOWN, "" }, /* 413 */
  { "fa\'a", FAhA, "towards point" }, /* 414 */
  { "fa\'e", BAI, "reverse of" }, /* 415 */
  { "fa\'i", VUhU, "reciprocal of" }, /* 416 */
  { "fa\'o", FAhO, "end of text" }, /* 417 */
  { "fa\'u", JOI, "and respectively" }, /* 418 */
  { "", UNKNOWN, "" }, /* 419 */
  { "fe", FA, "2nd sumti place" }, /* 420 */
  { "", UNKNOWN, "" }, /* 421 */
  { "", UNKNOWN, "" }, /* 422 */
  { "fei", PA, "hex digit B" }, /* 423 */
  { "", UNKNOWN, "" }, /* 424 */
  { "", UNKNOWN, "" }, /* 425 */
  { "", UNKNOWN, "" }, /* 426 */
  { "", UNKNOWN, "" }, /* 427 */
  { "fe\'a", VUhU, "nth root of" }, /* 428 */
  { "fe\'e", FEhE, "space aspects" }, /* 429 */
  { "fe\'i", VUhU, "divided by" }, /* 430 */
  { "fe\'o", COI, "over and out" }, /* 431 */
  { "fe\'u", FEhU, "end modal selbri" }, /* 432 */
  { "", UNKNOWN, "" }, /* 433 */
  { "fi", FA, "3rd sumti place" }, /* 434 */
  { "", UNKNOWN, "" }, /* 435 */
  { "", UNKNOWN, "" }, /* 436 */
  { "", UNKNOWN, "" }, /* 437 */
  { "", UNKNOWN, "" }, /* 438 */
  { "", UNKNOWN, "" }, /* 439 */
  { "", UNKNOWN, "" }, /* 440 */
  { "", UNKNOWN, "" }, /* 441 */
  { "fi\'a", FA, "sumti place ?" }, /* 442 */
  { "fi\'e", BAI, "created by" }, /* 443 */
  { "fi\'i", COI, "hospitality" }, /* 444 */
  { "fi\'o", FIhO, "selbri to modal" }, /* 445 */
  { "fi\'u", PA, "fraction slash" }, /* 446 */
  { "", UNKNOWN, "" }, /* 447 */
  { "fo", FA, "4th sumti place" }, /* 448 */
  { "", UNKNOWN, "" }, /* 449 */
  { "", UNKNOWN, "" }, /* 450 */
  { "foi", FOI, "end composite lerfu" }, /* 451 */
  { "", UNKNOWN, "" }, /* 452 */
  { "", UNKNOWN, "" }, /* 453 */
  { "", UNKNOWN, "" }, /* 454 */
  { "", UNKNOWN, "" }, /* 455 */
  { "fo\'a", KOhA, "it-6" }, /* 456 */
  { "fo\'e", KOhA, "it-7" }, /* 457 */
  { "fo\'i", KOhA, "it-8" }, /* 458 */
  { "fo\'o", KOhA, "it-9" }, /* 459 */
  { "fo\'u", KOhA, "it-10" }, /* 460 */
  { "", UNKNOWN, "" }, /* 461 */
  { "fu", FA, "5th sumti place" }, /* 462 */
  { "", UNKNOWN, "" }, /* 463 */
  { "", UNKNOWN, "" }, /* 464 */
  { "", UNKNOWN, "" }, /* 465 */
  { "", UNKNOWN, "" }, /* 466 */
  { "", UNKNOWN, "" }, /* 467 */
  { "", UNKNOWN, "" }, /* 468 */
  { "", UNKNOWN, "" }, /* 469 */
  { "fu\'a", FUhA, "reverse Polish" }, /* 470 */
  { "fu\'e", FUhE, "indicator scope" }, /* 471 */
  { "fu\'i", UI, "easy" }, /* 472 */
  { "fu\'o", FUhO, "end indicator scope" }, /* 473 */
  { "fu\'u", VUhU, "unspecif operator" }, /* 474 */
  { "", UNKNOWN, "" }, /* 475 */
  { "fy", BY, "f" }, /* 476 */
  { "", UNKNOWN, "" }, /* 477 */
  { "", UNKNOWN, "" }, /* 478 */
  { "", UNKNOWN, "" }, /* 479 */
  { "", UNKNOWN, "" }, /* 480 */
  { "", UNKNOWN, "" }, /* 481 */
  { "", UNKNOWN, "" }, /* 482 */
  { "", UNKNOWN, "" }, /* 483 */
  { "", UNKNOWN, "" }, /* 484 */
  { "", UNKNOWN, "" }, /* 485 */
  { "", UNKNOWN, "" }, /* 486 */
  { "", UNKNOWN, "" }, /* 487 */
  { "", UNKNOWN, "" }, /* 488 */
  { "", UNKNOWN, "" }, /* 489 */
  { "", UNKNOWN, "" }, /* 490 */
  { "", UNKNOWN, "" }, /* 491 */
  { "", UNKNOWN, "" }, /* 492 */
  { "", UNKNOWN, "" }, /* 493 */
  { "", UNKNOWN, "" }, /* 494 */
  { "", UNKNOWN, "" }, /* 495 */
  { "", UNKNOWN, "" }, /* 496 */
  { "", UNKNOWN, "" }, /* 497 */
  { "", UNKNOWN, "" }, /* 498 */
  { "", UNKNOWN, "" }, /* 499 */
  { "", UNKNOWN, "" }, /* 500 */
  { "", UNKNOWN, "" }, /* 501 */
  { "", UNKNOWN, "" }, /* 502 */
  { "", UNKNOWN, "" }, /* 503 */
  { "ga", GA, "fore or" }, /* 504 */
  { "", UNKNOWN, "" }, /* 505 */
  { "", UNKNOWN, "" }, /* 506 */
  { "gai", PA, "hex digit C" }, /* 507 */
  { "", UNKNOWN, "" }, /* 508 */
  { "gau", BAI, "with active agent" }, /* 509 */
  { "", UNKNOWN, "" }, /* 510 */
  { "", UNKNOWN, "" }, /* 511 */
  { "ga\'a", BAI, "to observer" }, /* 512 */
  { "ga\'e", BY, "upper-case shift" }, /* 513 */
  { "ga\'i", UI, "hauteur" }, /* 514 */
  { "ga\'o", GAhO, "inclusive interval" }, /* 515 */
  { "ga\'u", FAhA, "above" }, /* 516 */
  { "", UNKNOWN, "" }, /* 517 */
  { "ge", GA, "fore and" }, /* 518 */
  { "", UNKNOWN, "" }, /* 519 */
  { "", UNKNOWN, "" }, /* 520 */
  { "gei", VUhU, "exponential notation" }, /* 521 */
  { "", UNKNOWN, "" }, /* 522 */
  { "", UNKNOWN, "" }, /* 523 */
  { "", UNKNOWN, "" }, /* 524 */
  { "", UNKNOWN, "" }, /* 525 */
  { "ge\'a", VUhU, "null operator" }, /* 526 */
  { "ge\'e", UI, "unspecif emotion" }, /* 527 */
  { "ge\'i", GA, "fore conn ?" }, /* 528 */
  { "ge\'o", BY, "Greek shift" }, /* 529 */
  { "ge\'u", GEhU, "end relative phrase" }, /* 530 */
  { "", UNKNOWN, "" }, /* 531 */
  { "gi", GI, "connective medial" }, /* 532 */
  { "", UNKNOWN, "" }, /* 533 */
  { "", UNKNOWN, "" }, /* 534 */
  { "", UNKNOWN, "" }, /* 535 */
  { "", UNKNOWN, "" }, /* 536 */
  { "", UNKNOWN, "" }, /* 537 */
  { "", UNKNOWN, "" }, /* 538 */
  { "", UNKNOWN, "" }, /* 539 */
  { "gi\'a", GIhA, "bridi or" }, /* 540 */
  { "gi\'e", GIhA, "bridi and" }, /* 541 */
  { "gi\'i", GIhA, "bridi conn ?" }, /* 542 */
  { "gi\'o", GIhA, "bridi iff" }, /* 543 */
  { "gi\'u", GIhA, "bridi whether" }, /* 544 */
  { "", UNKNOWN, "" }, /* 545 */
  { "go", GA, "fore iff" }, /* 546 */
  { "", UNKNOWN, "" }, /* 547 */
  { "", UNKNOWN, "" }, /* 548 */
  { "goi", GOI, "pro-sumti assign" }, /* 549 */
  { "", UNKNOWN, "" }, /* 550 */
  { "", UNKNOWN, "" }, /* 551 */
  { "", UNKNOWN, "" }, /* 552 */
  { "", UNKNOWN, "" }, /* 553 */
  { "go\'a", GOhA, "recent bridi" }, /* 554 */
  { "go\'e", GOhA, "penultimate bridi" }, /* 555 */
  { "go\'i", GOhA, "last bridi" }, /* 556 */
  { "go\'o", GOhA, "future bridi" }, /* 557 */
  { "go\'u", GOhA, "earlier bridi" }, /* 558 */
  { "", UNKNOWN, "" }, /* 559 */
  { "gu", GA, "fore whether" }, /* 560 */
  { "", UNKNOWN, "" }, /* 561 */
  { "", UNKNOWN, "" }, /* 562 */
  { "", UNKNOWN, "" }, /* 563 */
  { "", UNKNOWN, "" }, /* 564 */
  { "", UNKNOWN, "" }, /* 565 */
  { "", UNKNOWN, "" }, /* 566 */
  { "", UNKNOWN, "" }, /* 567 */
  { "gu\'a", GUhA, "fore tanru or" }, /* 568 */
  { "gu\'e", GUhA, "fore tanru and" }, /* 569 */
  { "gu\'i", GUhA, "fore tanru conn ?" }, /* 570 */
  { "gu\'o", GUhA, "fore tanru iff" }, /* 571 */
  { "gu\'u", GUhA, "fore tanru whether" }, /* 572 */
  { "", UNKNOWN, "" }, /* 573 */
  { "gy", BY, "g" }, /* 574 */
  { "", UNKNOWN, "" }, /* 575 */
  { "", UNKNOWN, "" }, /* 576 */
  { "", UNKNOWN, "" }, /* 577 */
  { "", UNKNOWN, "" }, /* 578 */
  { "", UNKNOWN, "" }, /* 579 */
  { "", UNKNOWN, "" }, /* 580 */
  { "", UNKNOWN, "" }, /* 581 */
  { "", UNKNOWN, "" }, /* 582 */
  { "", UNKNOWN, "" }, /* 583 */
  { "", UNKNOWN, "" }, /* 584 */
  { "", UNKNOWN, "" }, /* 585 */
  { "", UNKNOWN, "" }, /* 586 */
  { "", UNKNOWN, "" }, /* 587 */
  { "", UNKNOWN, "" }, /* 588 */
  { "", UNKNOWN, "" }, /* 589 */
  { "", UNKNOWN, "" }, /* 590 */
  { "", UNKNOWN, "" }, /* 591 */
  { "", UNKNOWN, "" }, /* 592 */
  { "", UNKNOWN, "" }, /* 593 */
  { "", UNKNOWN, "" }, /* 594 */
  { "", UNKNOWN, "" }, /* 595 */
  { "", UNKNOWN, "" }, /* 596 */
  { "", UNKNOWN, "" }, /* 597 */
  { "", UNKNOWN, "" }, /* 598 */
  { "", UNKNOWN, "" }, /* 599 */
  { "", UNKNOWN, "" }, /* 600 */
  { "", UNKNOWN, "" }, /* 601 */
  { "ja", JA, "tanru or" }, /* 602 */
  { "", UNKNOWN, "" }, /* 603 */
  { "", UNKNOWN, "" }, /* 604 */
  { "jai", JAI, "modal conversion" }, /* 605 */
  { "", UNKNOWN, "" }, /* 606 */
  { "jau", PA, "hex digit D" }, /* 607 */
  { "", UNKNOWN, "" }, /* 608 */
  { "", UNKNOWN, "" }, /* 609 */
  { "ja\'a", NA, "bridi affirmer" }, /* 610 */
  { "ja\'e", BAI, "therefore result" }, /* 611 */
  { "ja\'i", BAI, "by rule" }, /* 612 */
  { "ja\'o", UI, "I conclude" }, /* 613 */
  { "", UNKNOWN, "" }, /* 614 */
  { "", UNKNOWN, "" }, /* 615 */
  { "je", JA, "tanru and" }, /* 616 */
  { "", UNKNOWN, "" }, /* 617 */
  { "", UNKNOWN, "" }, /* 618 */
  { "jei", NU, "truth abstract" }, /* 619 */
  { "", UNKNOWN, "" }, /* 620 */
  { "", UNKNOWN, "" }, /* 621 */
  { "", UNKNOWN, "" }, /* 622 */
  { "", UNKNOWN, "" }, /* 623 */
  { "je\'a", NAhE, "scalar affirmer" }, /* 624 */
  { "je\'e", COI, "roger" }, /* 625 */
  { "je\'i", JA, "tanru conn ?" }, /* 626 */
  { "je\'o", BY, "Hebrew shift" }, /* 627 */
  { "je\'u", UI, "truth" }, /* 628 */
  { "", UNKNOWN, "" }, /* 629 */
  { "ji", A, "sumti conn ?" }, /* 630 */
  { "", UNKNOWN, "" }, /* 631 */
  { "", UNKNOWN, "" }, /* 632 */
  { "", UNKNOWN, "" }, /* 633 */
  { "", UNKNOWN, "" }, /* 634 */
  { "", UNKNOWN, "" }, /* 635 */
  { "", UNKNOWN, "" }, /* 636 */
  { "", UNKNOWN, "" }, /* 637 */
  { "ji\'a", UI, "in addition" }, /* 638 */
  { "ji\'e", BAI, "up to limit" }, /* 639 */
  { "ji\'i", PA, "approximately" }, /* 640 */
  { "ji\'o", BAI, "under direction of" }, /* 641 */
  { "ji\'u", BAI, "based on" }, /* 642 */
  { "", UNKNOWN, "" }, /* 643 */
  { "jo", JA, "tanru iff" }, /* 644 */
  { "", UNKNOWN, "" }, /* 645 */
  { "", UNKNOWN, "" }, /* 646 */
  { "joi", JOI, "in a mass with" }, /* 647 */
  { "", UNKNOWN, "" }, /* 648 */
  { "", UNKNOWN, "" }, /* 649 */
  { "", UNKNOWN, "" }, /* 650 */
  { "", UNKNOWN, "" }, /* 651 */
  { "jo\'a", UI, "metalinguistic yes" }, /* 652 */
  { "jo\'e", JOI, "union" }, /* 653 */
  { "jo\'i", JOhI, "array" }, /* 654 */
  { "jo\'o", BY, "Arabic shift" }, /* 655 */
  { "jo\'u", JOI, "in common with" }, /* 656 */
  { "", UNKNOWN, "" }, /* 657 */
  { "ju", JA, "tanru whether" }, /* 658 */
  { "", UNKNOWN, "" }, /* 659 */
  { "", UNKNOWN, "" }, /* 660 */
  { "", UNKNOWN, "" }, /* 661 */
  { "", UNKNOWN, "" }, /* 662 */
  { "", UNKNOWN, "" }, /* 663 */
  { "", UNKNOWN, "" }, /* 664 */
  { "", UNKNOWN, "" }, /* 665 */
  { "ju\'a", UI, "I state" }, /* 666 */
  { "", UNKNOWN, "" }, /* 667 */
  { "ju\'i", COI, "attention" }, /* 668 */
  { "ju\'o", UI, "certainty" }, /* 669 */
  { "ju\'u", VUhU, "number base" }, /* 670 */
  { "", UNKNOWN, "" }, /* 671 */
  { "jy", BY, "j" }, /* 672 */
  { "", UNKNOWN, "" }, /* 673 */
  { "", UNKNOWN, "" }, /* 674 */
  { "", UNKNOWN, "" }, /* 675 */
  { "", UNKNOWN, "" }, /* 676 */
  { "", UNKNOWN, "" }, /* 677 */
  { "", UNKNOWN, "" }, /* 678 */
  { "", UNKNOWN, "" }, /* 679 */
  { "", UNKNOWN, "" }, /* 680 */
  { "", UNKNOWN, "" }, /* 681 */
  { "", UNKNOWN, "" }, /* 682 */
  { "", UNKNOWN, "" }, /* 683 */
  { "", UNKNOWN, "" }, /* 684 */
  { "", UNKNOWN, "" }, /* 685 */
  { "", UNKNOWN, "" }, /* 686 */
  { "", UNKNOWN, "" }, /* 687 */
  { "", UNKNOWN, "" }, /* 688 */
  { "", UNKNOWN, "" }, /* 689 */
  { "", UNKNOWN, "" }, /* 690 */
  { "", UNKNOWN, "" }, /* 691 */
  { "", UNKNOWN, "" }, /* 692 */
  { "", UNKNOWN, "" }, /* 693 */
  { "", UNKNOWN, "" }, /* 694 */
  { "", UNKNOWN, "" }, /* 695 */
  { "", UNKNOWN, "" }, /* 696 */
  { "", UNKNOWN, "" }, /* 697 */
  { "", UNKNOWN, "" }, /* 698 */
  { "", UNKNOWN, "" }, /* 699 */
  { "ka", NU, "property abstract" }, /* 700 */
  { "", UNKNOWN, "" }, /* 701 */
  { "", UNKNOWN, "" }, /* 702 */
  { "kai", BAI, "characterizing" }, /* 703 */
  { "", UNKNOWN, "" }, /* 704 */
  { "kau", UI, "indirect question" }, /* 705 */
  { "", UNKNOWN, "" }, /* 706 */
  { "", UNKNOWN, "" }, /* 707 */
  { "ka\'a", BAI, "gone to by" }, /* 708 */
  { "ka\'e", CAhA, "innately capable of" }, /* 709 */
  { "ka\'i", BAI, "represented by" }, /* 710 */
  { "ka\'o", PA, "imaginary i" }, /* 711 */
  { "ka\'u", UI, "I know culturally" }, /* 712 */
  { "", UNKNOWN, "" }, /* 713 */
  { "ke", KE, "start grouping" }, /* 714 */
  { "", UNKNOWN, "" }, /* 715 */
  { "", UNKNOWN, "" }, /* 716 */
  { "kei", KEI, "end abstraction" }, /* 717 */
  { "", UNKNOWN, "" }, /* 718 */
  { "", UNKNOWN, "" }, /* 719 */
  { "", UNKNOWN, "" }, /* 720 */
  { "", UNKNOWN, "" }, /* 721 */
  { "ke\'a", KOhA, "relativized it" }, /* 722 */
  { "ke\'e", KEhE, "end grouping" }, /* 723 */
  { "ke\'i", GAhO, "exclusive interval" }, /* 724 */
  { "ke\'o", COI, "please repeat" }, /* 725 */
  { "ke\'u", UI, "repeating" }, /* 726 */
  { "", UNKNOWN, "" }, /* 727 */
  { "ki", KI, "tense default" }, /* 728 */
  { "", UNKNOWN, "" }, /* 729 */
  { "", UNKNOWN, "" }, /* 730 */
  { "", UNKNOWN, "" }, /* 731 */
  { "", UNKNOWN, "" }, /* 732 */
  { "", UNKNOWN, "" }, /* 733 */
  { "", UNKNOWN, "" }, /* 734 */
  { "", UNKNOWN, "" }, /* 735 */
  { "ki\'a", UI, "textual confusion" }, /* 736 */
  { "ki\'e", COI, "thanks" }, /* 737 */
  { "ki\'i", BAI, "as a relation of" }, /* 738 */
  { "ki\'o", PA, "number comma" }, /* 739 */
  { "ki\'u", BAI, "because of reason" }, /* 740 */
  { "", UNKNOWN, "" }, /* 741 */
  { "ko", KOhA, "imperative" }, /* 742 */
  { "", UNKNOWN, "" }, /* 743 */
  { "", UNKNOWN, "" }, /* 744 */
  { "koi", BAI, "bounded by" }, /* 745 */
  { "", UNKNOWN, "" }, /* 746 */
  { "", UNKNOWN, "" }, /* 747 */
  { "", UNKNOWN, "" }, /* 748 */
  { "", UNKNOWN, "" }, /* 749 */
  { "ko\'a", KOhA, "it-1" }, /* 750 */
  { "ko\'e", KOhA, "it-2" }, /* 751 */
  { "ko\'i", KOhA, "it-3" }, /* 752 */
  { "ko\'o", KOhA, "it-4" }, /* 753 */
  { "ko\'u", KOhA, "it-5" }, /* 754 */
  { "", UNKNOWN, "" }, /* 755 */
  { "ku", KU, "end sumti" }, /* 756 */
  { "", UNKNOWN, "" }, /* 757 */
  { "", UNKNOWN, "" }, /* 758 */
  { "", UNKNOWN, "" }, /* 759 */
  { "", UNKNOWN, "" }, /* 760 */
  { "", UNKNOWN, "" }, /* 761 */
  { "", UNKNOWN, "" }, /* 762 */
  { "", UNKNOWN, "" }, /* 763 */
  { "ku\'a", JOI, "intersection" }, /* 764 */
  { "ku\'e", KUhE, "end mex forethought" }, /* 765 */
  { "ku\'i", UI, "however" }, /* 766 */
  { "ku\'o", KUhO, "end relative clause" }, /* 767 */
  { "ku\'u", BAI, "in culture" }, /* 768 */
  { "", UNKNOWN, "" }, /* 769 */
  { "ky", BY, "k" }, /* 770 */
  { "", UNKNOWN, "" }, /* 771 */
  { "", UNKNOWN, "" }, /* 772 */
  { "", UNKNOWN, "" }, /* 773 */
  { "", UNKNOWN, "" }, /* 774 */
  { "", UNKNOWN, "" }, /* 775 */
  { "", UNKNOWN, "" }, /* 776 */
  { "", UNKNOWN, "" }, /* 777 */
  { "", UNKNOWN, "" }, /* 778 */
  { "", UNKNOWN, "" }, /* 779 */
  { "", UNKNOWN, "" }, /* 780 */
  { "", UNKNOWN, "" }, /* 781 */
  { "", UNKNOWN, "" }, /* 782 */
  { "", UNKNOWN, "" }, /* 783 */
  { "", UNKNOWN, "" }, /* 784 */
  { "", UNKNOWN, "" }, /* 785 */
  { "", UNKNOWN, "" }, /* 786 */
  { "", UNKNOWN, "" }, /* 787 */
  { "", UNKNOWN, "" }, /* 788 */
  { "", UNKNOWN, "" }, /* 789 */
  { "", UNKNOWN, "" }, /* 790 */
  { "", UNKNOWN, "" }, /* 791 */
  { "", UNKNOWN, "" }, /* 792 */
  { "", UNKNOWN, "" }, /* 793 */
  { "", UNKNOWN, "" }, /* 794 */
  { "", UNKNOWN, "" }, /* 795 */
  { "", UNKNOWN, "" }, /* 796 */
  { "", UNKNOWN, "" }, /* 797 */
  { "la", LA, "that named" }, /* 798 */
  { "", UNKNOWN, "" }, /* 799 */
  { "", UNKNOWN, "" }, /* 800 */
  { "lai", LA, "the mass of named" }, /* 801 */
  { "", UNKNOWN, "" }, /* 802 */
  { "lau", LAU, "punctuation mark" }, /* 803 */
  { "", UNKNOWN, "" }, /* 804 */
  { "", UNKNOWN, "" }, /* 805 */
  { "la\'a", UI, "probability" }, /* 806 */
  { "la\'e", LAhE, "the referent of" }, /* 807 */
  { "la\'i", LA, "the set of named" }, /* 808 */
  { "la\'o", ZOI, "the non-Lojban named" }, /* 809 */
  { "la\'u", BAI, "quantifying" }, /* 810 */
  { "", UNKNOWN, "" }, /* 811 */
  { "le", LE, "the described" }, /* 812 */
  { "", UNKNOWN, "" }, /* 813 */
  { "", UNKNOWN, "" }, /* 814 */
  { "lei", LE, "the mass described" }, /* 815 */
  { "", UNKNOWN, "" }, /* 816 */
  { "", UNKNOWN, "" }, /* 817 */
  { "", UNKNOWN, "" }, /* 818 */
  { "", UNKNOWN, "" }, /* 819 */
  { "le\'a", BAI, "in category" }, /* 820 */
  { "le\'e", LE, "the stereotypical" }, /* 821 */
  { "le\'i", LE, "the set described" }, /* 822 */
  { "le\'o", UI, "aggressive" }, /* 823 */
  { "le\'u", LEhU, "end error quote" }, /* 824 */
  { "", UNKNOWN, "" }, /* 825 */
  { "li", LI, "the number" }, /* 826 */
  { "", UNKNOWN, "" }, /* 827 */
  { "", UNKNOWN, "" }, /* 828 */
  { "", UNKNOWN, "" }, /* 829 */
  { "", UNKNOWN, "" }, /* 830 */
  { "", UNKNOWN, "" }, /* 831 */
  { "", UNKNOWN, "" }, /* 832 */
  { "", UNKNOWN, "" }, /* 833 */
  { "li\'a", UI, "clearly" }, /* 834 */
  { "li\'e", BAI, "preceded by" }, /* 835 */
  { "li\'i", NU, "experience abstract" }, /* 836 */
  { "li\'o", UI, "omitted text" }, /* 837 */
  { "li\'u", LIhU, "end quote" }, /* 838 */
  { "", UNKNOWN, "" }, /* 839 */
  { "lo", LE, "the really is" }, /* 840 */
  { "", UNKNOWN, "" }, /* 841 */
  { "", UNKNOWN, "" }, /* 842 */
  { "loi", LE, "the mass really is" }, /* 843 */
  { "", UNKNOWN, "" }, /* 844 */
  { "", UNKNOWN, "" }, /* 845 */
  { "", UNKNOWN, "" }, /* 846 */
  { "", UNKNOWN, "" }, /* 847 */
  { "lo\'a", BY, "Lojban shift" }, /* 848 */
  { "lo\'e", LE, "the typical" }, /* 849 */
  { "lo\'i", LE, "the set really is" }, /* 850 */
  { "lo\'o", LOhO, "end mex sumti" }, /* 851 */
  { "lo\'u", LOhU, "error quote" }, /* 852 */
  { "", UNKNOWN, "" }, /* 853 */
  { "lu", LU, "quote" }, /* 854 */
  { "", UNKNOWN, "" }, /* 855 */
  { "", UNKNOWN, "" }, /* 856 */
  { "", UNKNOWN, "" }, /* 857 */
  { "", UNKNOWN, "" }, /* 858 */
  { "", UNKNOWN, "" }, /* 859 */
  { "", UNKNOWN, "" }, /* 860 */
  { "", UNKNOWN, "" }, /* 861 */
  { "lu\'a", LAhE, "the individuals of" }, /* 862 */
  { "lu\'e", LAhE, "the symbol for" }, /* 863 */
  { "lu\'i", LAhE, "the set composed of" }, /* 864 */
  { "lu\'o", LAhE, "the mass composed of" }, /* 865 */
  { "lu\'u", LUhU, "end sumti qualifiers" }, /* 866 */
  { "", UNKNOWN, "" }, /* 867 */
  { "ly", BY, "l" }, /* 868 */
  { "", UNKNOWN, "" }, /* 869 */
  { "", UNKNOWN, "" }, /* 870 */
  { "", UNKNOWN, "" }, /* 871 */
  { "", UNKNOWN, "" }, /* 872 */
  { "", UNKNOWN, "" }, /* 873 */
  { "", UNKNOWN, "" }, /* 874 */
  { "", UNKNOWN, "" }, /* 875 */
  { "", UNKNOWN, "" }, /* 876 */
  { "", UNKNOWN, "" }, /* 877 */
  { "", UNKNOWN, "" }, /* 878 */
  { "", UNKNOWN, "" }, /* 879 */
  { "", UNKNOWN, "" }, /* 880 */
  { "", UNKNOWN, "" }, /* 881 */
  { "", UNKNOWN, "" }, /* 882 */
  { "", UNKNOWN, "" }, /* 883 */
  { "", UNKNOWN, "" }, /* 884 */
  { "", UNKNOWN, "" }, /* 885 */
  { "", UNKNOWN, "" }, /* 886 */
  { "", UNKNOWN, "" }, /* 887 */
  { "", UNKNOWN, "" }, /* 888 */
  { "", UNKNOWN, "" }, /* 889 */
  { "", UNKNOWN, "" }, /* 890 */
  { "", UNKNOWN, "" }, /* 891 */
  { "", UNKNOWN, "" }, /* 892 */
  { "", UNKNOWN, "" }, /* 893 */
  { "", UNKNOWN, "" }, /* 894 */
  { "", UNKNOWN, "" }, /* 895 */
  { "ma", KOhA, "sumti ?" }, /* 896 */
  { "", UNKNOWN, "" }, /* 897 */
  { "", UNKNOWN, "" }, /* 898 */
  { "mai", MAI, "sentence ordinal" }, /* 899 */
  { "", UNKNOWN, "" }, /* 900 */
  { "mau", BAI, "exceeded by" }, /* 901 */
  { "", UNKNOWN, "" }, /* 902 */
  { "", UNKNOWN, "" }, /* 903 */
  { "ma\'a", KOhA, "we with you" }, /* 904 */
  { "ma\'e", BAI, "material object" }, /* 905 */
  { "ma\'i", BAI, "in reference frame" }, /* 906 */
  { "ma\'o", MAhO, "operand to operator" }, /* 907 */
  { "ma\'u", PA, "positive number" }, /* 908 */
  { "", UNKNOWN, "" }, /* 909 */
  { "me", ME, "sumti to selbri" }, /* 910 */
  { "", UNKNOWN, "" }, /* 911 */
  { "", UNKNOWN, "" }, /* 912 */
  { "mei", MOI, "cardinal selbri" }, /* 913 */
  { "", UNKNOWN, "" }, /* 914 */
  { "", UNKNOWN, "" }, /* 915 */
  { "", UNKNOWN, "" }, /* 916 */
  { "", UNKNOWN, "" }, /* 917 */
  { "me\'a", BAI, "undercut by" }, /* 918 */
  { "me\'e", BAI, "with name" }, /* 919 */
  { "me\'i", PA, "less than" }, /* 920 */
  { "me\'o", LI, "the mex" }, /* 921 */
  { "me\'u", MEhU, "end sumti to selbri" }, /* 922 */
  { "", UNKNOWN, "" }, /* 923 */
  { "mi", KOhA, "me" }, /* 924 */
  { "", UNKNOWN, "" }, /* 925 */
  { "", UNKNOWN, "" }, /* 926 */
  { "", UNKNOWN, "" }, /* 927 */
  { "", UNKNOWN, "" }, /* 928 */
  { "", UNKNOWN, "" }, /* 929 */
  { "", UNKNOWN, "" }, /* 930 */
  { "", UNKNOWN, "" }, /* 931 */
  { "mi\'a", KOhA, "we, not you" }, /* 932 */
  { "mi\'e", COI, "self-introduction" }, /* 933 */
  { "mi\'i", BIhI, "center-range" }, /* 934 */
  { "mi\'o", KOhA, "me and you" }, /* 935 */
  { "mi\'u", UI, "ditto" }, /* 936 */
  { "", UNKNOWN, "" }, /* 937 */
  { "mo", GOhA, "bridi ?" }, /* 938 */
  { "", UNKNOWN, "" }, /* 939 */
  { "", UNKNOWN, "" }, /* 940 */
  { "moi", MOI, "ordinal selbri" }, /* 941 */
  { "", UNKNOWN, "" }, /* 942 */
  { "", UNKNOWN, "" }, /* 943 */
  { "", UNKNOWN, "" }, /* 944 */
  { "", UNKNOWN, "" }, /* 945 */
  { "mo\'a", PA, "too few" }, /* 946 */
  { "mo\'e", MOhE, "sumti to operand" }, /* 947 */
  { "mo\'i", MOhI, "space motion" }, /* 948 */
  { "mo\'o", MAI, "section ordinal" }, /* 949 */
  { "mo\'u", ZAhO, "completive" }, /* 950 */
  { "", UNKNOWN, "" }, /* 951 */
  { "mu", PA, "5" }, /* 952 */
  { "", UNKNOWN, "" }, /* 953 */
  { "", UNKNOWN, "" }, /* 954 */
  { "", UNKNOWN, "" }, /* 955 */
  { "", UNKNOWN, "" }, /* 956 */
  { "", UNKNOWN, "" }, /* 957 */
  { "", UNKNOWN, "" }, /* 958 */
  { "", UNKNOWN, "" }, /* 959 */
  { "mu\'a", UI, "for example" }, /* 960 */
  { "mu\'e", NU, "point-event abstract" }, /* 961 */
  { "mu\'i", BAI, "because of motive" }, /* 962 */
  { "mu\'o", COI, "over" }, /* 963 */
  { "mu\'u", BAI, "exemplified by" }, /* 964 */
  { "", UNKNOWN, "" }, /* 965 */
  { "my", BY, "m" }, /* 966 */
  { "", UNKNOWN, "" }, /* 967 */
  { "", UNKNOWN, "" }, /* 968 */
  { "", UNKNOWN, "" }, /* 969 */
  { "", UNKNOWN, "" }, /* 970 */
  { "", UNKNOWN, "" }, /* 971 */
  { "", UNKNOWN, "" }, /* 972 */
  { "", UNKNOWN, "" }, /* 973 */
  { "", UNKNOWN, "" }, /* 974 */
  { "", UNKNOWN, "" }, /* 975 */
  { "", UNKNOWN, "" }, /* 976 */
  { "", UNKNOWN, "" }, /* 977 */
  { "", UNKNOWN, "" }, /* 978 */
  { "", UNKNOWN, "" }, /* 979 */
  { "", UNKNOWN, "" }, /* 980 */
  { "", UNKNOWN, "" }, /* 981 */
  { "", UNKNOWN, "" }, /* 982 */
  { "", UNKNOWN, "" }, /* 983 */
  { "", UNKNOWN, "" }, /* 984 */
  { "", UNKNOWN, "" }, /* 985 */
  { "", UNKNOWN, "" }, /* 986 */
  { "", UNKNOWN, "" }, /* 987 */
  { "", UNKNOWN, "" }, /* 988 */
  { "", UNKNOWN, "" }, /* 989 */
  { "", UNKNOWN, "" }, /* 990 */
  { "", UNKNOWN, "" }, /* 991 */
  { "", UNKNOWN, "" }, /* 992 */
  { "", UNKNOWN, "" }, /* 993 */
  { "na", NA, "bridi negator" }, /* 994 */
  { "", UNKNOWN, "" }, /* 995 */
  { "", UNKNOWN, "" }, /* 996 */
  { "nai", NAI, "negate last word" }, /* 997 */
  { "", UNKNOWN, "" }, /* 998 */
  { "nau", CUhE, "reference point" }, /* 999 */
  { "", UNKNOWN, "" }, /* 1000 */
  { "", UNKNOWN, "" }, /* 1001 */
  { "na\'a", BY, "cancel shifts" }, /* 1002 */
  { "na\'e", NAhE, "scalar contrary" }, /* 1003 */
  { "na\'i", UI, "metalinguistic not" }, /* 1004 */
  { "na\'o", TAhE, "typically" }, /* 1005 */
  { "na\'u", NAhU, "selbri to operator" }, /* 1006 */
  { "", UNKNOWN, "" }, /* 1007 */
  { "ne", GOI, "incidental phrase" }, /* 1008 */
  { "", UNKNOWN, "" }, /* 1009 */
  { "", UNKNOWN, "" }, /* 1010 */
  { "nei", GOhA, "current bridi" }, /* 1011 */
  { "", UNKNOWN, "" }, /* 1012 */
  { "", UNKNOWN, "" }, /* 1013 */
  { "", UNKNOWN, "" }, /* 1014 */
  { "", UNKNOWN, "" }, /* 1015 */
  { "ne\'a", FAhA, "next to" }, /* 1016 */
  { "", UNKNOWN, "" }, /* 1017 */
  { "ne\'i", FAhA, "within" }, /* 1018 */
  { "ne\'o", VUhU, "factorial" }, /* 1019 */
  { "ne\'u", FAhA, "south of" }, /* 1020 */
  { "", UNKNOWN, "" }, /* 1021 */
  { "ni", NU, "amount abstract" }, /* 1022 */
  { "", UNKNOWN, "" }, /* 1023 */
  { "", UNKNOWN, "" }, /* 1024 */
  { "", UNKNOWN, "" }, /* 1025 */
  { "", UNKNOWN, "" }, /* 1026 */
  { "", UNKNOWN, "" }, /* 1027 */
  { "", UNKNOWN, "" }, /* 1028 */
  { "", UNKNOWN, "" }, /* 1029 */
  { "ni\'a", FAhA, "below" }, /* 1030 */
  { "ni\'e", NIhE, "selbri to operand" }, /* 1031 */
  { "ni\'i", BAI, "because of logic" }, /* 1032 */
  { "ni\'o", NIhO, "new topic" }, /* 1033 */
  { "ni\'u", PA, "negative number" }, /* 1034 */
  { "", UNKNOWN, "" }, /* 1035 */
  { "no", PA, "0" }, /* 1036 */
  { "", UNKNOWN, "" }, /* 1037 */
  { "", UNKNOWN, "" }, /* 1038 */
  { "noi", NOI, "incidental clause" }, /* 1039 */
  { "", UNKNOWN, "" }, /* 1040 */
  { "", UNKNOWN, "" }, /* 1041 */
  { "", UNKNOWN, "" }, /* 1042 */
  { "", UNKNOWN, "" }, /* 1043 */
  { "no\'a", GOhA, "next outer bridi" }, /* 1044 */
  { "no\'e", NAhE, "scalar midpoint not" }, /* 1045 */
  { "no\'i", NIhO, "old topic" }, /* 1046 */
  { "no\'o", PA, "typical value" }, /* 1047 */
  { "no\'u", GOI, "incidental identity" }, /* 1048 */
  { "", UNKNOWN, "" }, /* 1049 */
  { "nu", NU, "event abstract" }, /* 1050 */
  { "", UNKNOWN, "" }, /* 1051 */
  { "", UNKNOWN, "" }, /* 1052 */
  { "", UNKNOWN, "" }, /* 1053 */
  { "", UNKNOWN, "" }, /* 1054 */
  { "", UNKNOWN, "" }, /* 1055 */
  { "", UNKNOWN, "" }, /* 1056 */
  { "", UNKNOWN, "" }, /* 1057 */
  { "nu\'a", NUhA, "operator to selbri" }, /* 1058 */
  { "nu\'e", COI, "promise" }, /* 1059 */
  { "nu\'i", NUhI, "start termset" }, /* 1060 */
  { "nu\'o", CAhA, "can but has not" }, /* 1061 */
  { "nu\'u", NUhU, "end termset" }, /* 1062 */
  { "", UNKNOWN, "" }, /* 1063 */
  { "ny", BY, "n" }, /* 1064 */
  { "", UNKNOWN, "" }, /* 1065 */
  { "", UNKNOWN, "" }, /* 1066 */
  { "", UNKNOWN, "" }, /* 1067 */
  { "", UNKNOWN, "" }, /* 1068 */
  { "", UNKNOWN, "" }, /* 1069 */
  { "", UNKNOWN, "" }, /* 1070 */
  { "", UNKNOWN, "" }, /* 1071 */
  { "", UNKNOWN, "" }, /* 1072 */
  { "", UNKNOWN, "" }, /* 1073 */
  { "", UNKNOWN, "" }, /* 1074 */
  { "", UNKNOWN, "" }, /* 1075 */
  { "", UNKNOWN, "" }, /* 1076 */
  { "", UNKNOWN, "" }, /* 1077 */
  { "", UNKNOWN, "" }, /* 1078 */
  { "", UNKNOWN, "" }, /* 1079 */
  { "", UNKNOWN, "" }, /* 1080 */
  { "", UNKNOWN, "" }, /* 1081 */
  { "", UNKNOWN, "" }, /* 1082 */
  { "", UNKNOWN, "" }, /* 1083 */
  { "", UNKNOWN, "" }, /* 1084 */
  { "", UNKNOWN, "" }, /* 1085 */
  { "", UNKNOWN, "" }, /* 1086 */
  { "", UNKNOWN, "" }, /* 1087 */
  { "", UNKNOWN, "" }, /* 1088 */
  { "", UNKNOWN, "" }, /* 1089 */
  { "", UNKNOWN, "" }, /* 1090 */
  { "", UNKNOWN, "" }, /* 1091 */
  { "pa", PA, "1" }, /* 1092 */
  { "", UNKNOWN, "" }, /* 1093 */
  { "", UNKNOWN, "" }, /* 1094 */
  { "pai", PA, "pi" }, /* 1095 */
  { "", UNKNOWN, "" }, /* 1096 */
  { "pau", UI, "question follows" }, /* 1097 */
  { "", UNKNOWN, "" }, /* 1098 */
  { "", UNKNOWN, "" }, /* 1099 */
  { "pa\'a", BAI, "in addition to" }, /* 1100 */
  { "pa\'e", UI, "justice" }, /* 1101 */
  { "pa\'i", VUhU, "ratio" }, /* 1102 */
  { "pa\'o", FAhA, "transfixing" }, /* 1103 */
  { "pa\'u", BAI, "having component" }, /* 1104 */
  { "", UNKNOWN, "" }, /* 1105 */
  { "pe", GOI, "restrictive phrase" }, /* 1106 */
  { "", UNKNOWN, "" }, /* 1107 */
  { "", UNKNOWN, "" }, /* 1108 */
  { "pei", CAI, "emotion ?" }, /* 1109 */
  { "", UNKNOWN, "" }, /* 1110 */
  { "", UNKNOWN, "" }, /* 1111 */
  { "", UNKNOWN, "" }, /* 1112 */
  { "", UNKNOWN, "" }, /* 1113 */
  { "pe\'a", PEhA, "start figurative" }, /* 1114 */
  { "", UNKNOWN, "" }, /* 1115 */
  { "pe\'i", UI, "I opine" }, /* 1116 */
  { "pe\'o", PEhO, "fore mex operator" }, /* 1117 */
  { "pe\'u", COI, "please" }, /* 1118 */
  { "", UNKNOWN, "" }, /* 1119 */
  { "pi", PA, "decimal point" }, /* 1120 */
  { "", UNKNOWN, "" }, /* 1121 */
  { "", UNKNOWN, "" }, /* 1122 */
  { "", UNKNOWN, "" }, /* 1123 */
  { "", UNKNOWN, "" }, /* 1124 */
  { "", UNKNOWN, "" }, /* 1125 */
  { "", UNKNOWN, "" }, /* 1126 */
  { "", UNKNOWN, "" }, /* 1127 */
  { "pi\'a", VUhU, "matrix of rows" }, /* 1128 */
  { "pi\'e", PA, "digit separator" }, /* 1129 */
  { "pi\'i", VUhU, "times" }, /* 1130 */
  { "pi\'o", BAI, "used by" }, /* 1131 */
  { "pi\'u", JOI, "cross product" }, /* 1132 */
  { "", UNKNOWN, "" }, /* 1133 */
  { "po", GOI, "is specific to" }, /* 1134 */
  { "", UNKNOWN, "" }, /* 1135 */
  { "", UNKNOWN, "" }, /* 1136 */
  { "poi", NOI, "restrictive clause" }, /* 1137 */
  { "", UNKNOWN, "" }, /* 1138 */
  { "", UNKNOWN, "" }, /* 1139 */
  { "", UNKNOWN, "" }, /* 1140 */
  { "", UNKNOWN, "" }, /* 1141 */
  { "po\'a", POhA, "end figurative" }, /* 1142 */
  { "po\'e", GOI, "which belongs to" }, /* 1143 */
  { "po\'i", BAI, "in the sequence" }, /* 1144 */
  { "po\'o", UI, "uniquely" }, /* 1145 */
  { "po\'u", GOI, "restrictive identity" }, /* 1146 */
  { "", UNKNOWN, "" }, /* 1147 */
  { "pu", PU, "before" }, /* 1148 */
  { "", UNKNOWN, "" }, /* 1149 */
  { "", UNKNOWN, "" }, /* 1150 */
  { "", UNKNOWN, "" }, /* 1151 */
  { "", UNKNOWN, "" }, /* 1152 */
  { "", UNKNOWN, "" }, /* 1153 */
  { "", UNKNOWN, "" }, /* 1154 */
  { "", UNKNOWN, "" }, /* 1155 */
  { "pu\'a", BAI, "pleased by" }, /* 1156 */
  { "pu\'e", BAI, "by process" }, /* 1157 */
  { "pu\'i", CAhA, "can and has" }, /* 1158 */
  { "pu\'o", ZAhO, "anticipative" }, /* 1159 */
  { "pu\'u", NU, "process abstract" }, /* 1160 */
  { "", UNKNOWN, "" }, /* 1161 */
  { "py", BY, "p" }, /* 1162 */
  { "", UNKNOWN, "" }, /* 1163 */
  { "", UNKNOWN, "" }, /* 1164 */
  { "", UNKNOWN, "" }, /* 1165 */
  { "", UNKNOWN, "" }, /* 1166 */
  { "", UNKNOWN, "" }, /* 1167 */
  { "", UNKNOWN, "" }, /* 1168 */
  { "", UNKNOWN, "" }, /* 1169 */
  { "", UNKNOWN, "" }, /* 1170 */
  { "", UNKNOWN, "" }, /* 1171 */
  { "", UNKNOWN, "" }, /* 1172 */
  { "", UNKNOWN, "" }, /* 1173 */
  { "", UNKNOWN, "" }, /* 1174 */
  { "", UNKNOWN, "" }, /* 1175 */
  { "", UNKNOWN, "" }, /* 1176 */
  { "", UNKNOWN, "" }, /* 1177 */
  { "", UNKNOWN, "" }, /* 1178 */
  { "", UNKNOWN, "" }, /* 1179 */
  { "", UNKNOWN, "" }, /* 1180 */
  { "", UNKNOWN, "" }, /* 1181 */
  { "", UNKNOWN, "" }, /* 1182 */
  { "", UNKNOWN, "" }, /* 1183 */
  { "", UNKNOWN, "" }, /* 1184 */
  { "", UNKNOWN, "" }, /* 1185 */
  { "", UNKNOWN, "" }, /* 1186 */
  { "", UNKNOWN, "" }, /* 1187 */
  { "", UNKNOWN, "" }, /* 1188 */
  { "", UNKNOWN, "" }, /* 1189 */
  { "ra", KOhA, "recent sumti" }, /* 1190 */
  { "", UNKNOWN, "" }, /* 1191 */
  { "", UNKNOWN, "" }, /* 1192 */
  { "rai", BAI, "with superlative" }, /* 1193 */
  { "", UNKNOWN, "" }, /* 1194 */
  { "rau", PA, "enough" }, /* 1195 */
  { "", UNKNOWN, "" }, /* 1196 */
  { "", UNKNOWN, "" }, /* 1197 */
  { "ra\'a", BAI, "pertained to by" }, /* 1198 */
  { "ra\'e", PA, "repeating decimal" }, /* 1199 */
  { "ra\'i", BAI, "from source" }, /* 1200 */
  { "ra\'o", RAhO, "pro-assign update" }, /* 1201 */
  { "ra\'u", UI, "chiefly" }, /* 1202 */
  { "", UNKNOWN, "" }, /* 1203 */
  { "re", PA, "2" }, /* 1204 */
  { "", UNKNOWN, "" }, /* 1205 */
  { "", UNKNOWN, "" }, /* 1206 */
  { "rei", PA, "hex digit E" }, /* 1207 */
  { "", UNKNOWN, "" }, /* 1208 */
  { "", UNKNOWN, "" }, /* 1209 */
  { "", UNKNOWN, "" }, /* 1210 */
  { "", UNKNOWN, "" }, /* 1211 */
  { "re\'a", VUhU, "transpose" }, /* 1212 */
  { "re\'e", UI, "spiritual" }, /* 1213 */
  { "re\'i", COI, "ready to receive" }, /* 1214 */
  { "re\'o", FAhA, "adjacent to" }, /* 1215 */
  { "", UNKNOWN, "" }, /* 1216 */
  { "", UNKNOWN, "" }, /* 1217 */
  { "ri", KOhA, "last sumti" }, /* 1218 */
  { "", UNKNOWN, "" }, /* 1219 */
  { "", UNKNOWN, "" }, /* 1220 */
  { "", UNKNOWN, "" }, /* 1221 */
  { "", UNKNOWN, "" }, /* 1222 */
  { "", UNKNOWN, "" }, /* 1223 */
  { "", UNKNOWN, "" }, /* 1224 */
  { "", UNKNOWN, "" }, /* 1225 */
  { "ri\'a", BAI, "because of cause" }, /* 1226 */
  { "ri\'e", UI, "release of emotion" }, /* 1227 */
  { "ri\'i", BAI, "experienced by" }, /* 1228 */
  { "ri\'o", VUhU, "integral" }, /* 1229 */
  { "ri\'u", FAhA, "on the right of" }, /* 1230 */
  { "", UNKNOWN, "" }, /* 1231 */
  { "ro", PA, "each" }, /* 1232 */
  { "", UNKNOWN, "" }, /* 1233 */
  { "", UNKNOWN, "" }, /* 1234 */
  { "roi", ROI, "quantified tense" }, /* 1235 */
  { "", UNKNOWN, "" }, /* 1236 */
  { "", UNKNOWN, "" }, /* 1237 */
  { "", UNKNOWN, "" }, /* 1238 */
  { "", UNKNOWN, "" }, /* 1239 */
  { "ro\'a", UI, "social" }, /* 1240 */
  { "ro\'e", UI, "mental" }, /* 1241 */
  { "ro\'i", UI, "emotional" }, /* 1242 */
  { "ro\'o", UI, "physical" }, /* 1243 */
  { "ro\'u", UI, "sexual" }, /* 1244 */
  { "", UNKNOWN, "" }, /* 1245 */
  { "ru", KOhA, "earlier sumti" }, /* 1246 */
  { "", UNKNOWN, "" }, /* 1247 */
  { "", UNKNOWN, "" }, /* 1248 */
  { "", UNKNOWN, "" }, /* 1249 */
  { "", UNKNOWN, "" }, /* 1250 */
  { "", UNKNOWN, "" }, /* 1251 */
  { "", UNKNOWN, "" }, /* 1252 */
  { "", UNKNOWN, "" }, /* 1253 */
  { "ru\'a", UI, "I postulate" }, /* 1254 */
  { "ru\'e", CAI, "weak emotion" }, /* 1255 */
  { "ru\'i", TAhE, "continuously" }, /* 1256 */
  { "ru\'o", BY, "Cyrillic shift" }, /* 1257 */
  { "ru\'u", FAhA, "surrounding" }, /* 1258 */
  { "", UNKNOWN, "" }, /* 1259 */
  { "ry", BY, "r" }, /* 1260 */
  { "", UNKNOWN, "" }, /* 1261 */
  { "", UNKNOWN, "" }, /* 1262 */
  { "", UNKNOWN, "" }, /* 1263 */
  { "", UNKNOWN, "" }, /* 1264 */
  { "", UNKNOWN, "" }, /* 1265 */
  { "", UNKNOWN, "" }, /* 1266 */
  { "", UNKNOWN, "" }, /* 1267 */
  { "", UNKNOWN, "" }, /* 1268 */
  { "", UNKNOWN, "" }, /* 1269 */
  { "", UNKNOWN, "" }, /* 1270 */
  { "", UNKNOWN, "" }, /* 1271 */
  { "", UNKNOWN, "" }, /* 1272 */
  { "", UNKNOWN, "" }, /* 1273 */
  { "", UNKNOWN, "" }, /* 1274 */
  { "", UNKNOWN, "" }, /* 1275 */
  { "", UNKNOWN, "" }, /* 1276 */
  { "", UNKNOWN, "" }, /* 1277 */
  { "", UNKNOWN, "" }, /* 1278 */
  { "", UNKNOWN, "" }, /* 1279 */
  { "", UNKNOWN, "" }, /* 1280 */
  { "", UNKNOWN, "" }, /* 1281 */
  { "", UNKNOWN, "" }, /* 1282 */
  { "", UNKNOWN, "" }, /* 1283 */
  { "", UNKNOWN, "" }, /* 1284 */
  { "", UNKNOWN, "" }, /* 1285 */
  { "", UNKNOWN, "" }, /* 1286 */
  { "", UNKNOWN, "" }, /* 1287 */
  { "sa", SA, "erase utterance" }, /* 1288 */
  { "", UNKNOWN, "" }, /* 1289 */
  { "", UNKNOWN, "" }, /* 1290 */
  { "sai", CAI, "strong emotion" }, /* 1291 */
  { "", UNKNOWN, "" }, /* 1292 */
  { "sau", BAI, "requiring" }, /* 1293 */
  { "", UNKNOWN, "" }, /* 1294 */
  { "", UNKNOWN, "" }, /* 1295 */
  { "sa\'a", UI, "editorial insertion" }, /* 1296 */
  { "sa\'e", UI, "precisely speaking" }, /* 1297 */
  { "sa\'i", VUhU, "matrix of columns" }, /* 1298 */
  { "sa\'o", VUhU, "derivative" }, /* 1299 */
  { "sa\'u", UI, "simply speaking" }, /* 1300 */
  { "", UNKNOWN, "" }, /* 1301 */
  { "se", SE, "2nd conversion" }, /* 1302 */
  { "", UNKNOWN, "" }, /* 1303 */
  { "", UNKNOWN, "" }, /* 1304 */
  { "sei", SEI, "discursive bridi" }, /* 1305 */
  { "", UNKNOWN, "" }, /* 1306 */
  { "", UNKNOWN, "" }, /* 1307 */
  { "", UNKNOWN, "" }, /* 1308 */
  { "", UNKNOWN, "" }, /* 1309 */
  { "se\'a", UI, "self-sufficiency" }, /* 1310 */
  { "se\'e", BY, "character code" }, /* 1311 */
  { "se\'i", UI, "self-oriented" }, /* 1312 */
  { "se\'o", UI, "I know internally" }, /* 1313 */
  { "se\'u", SEhU, "end discursive" }, /* 1314 */
  { "", UNKNOWN, "" }, /* 1315 */
  { "si", SI, "erase word" }, /* 1316 */
  { "", UNKNOWN, "" }, /* 1317 */
  { "", UNKNOWN, "" }, /* 1318 */
  { "", UNKNOWN, "" }, /* 1319 */
  { "", UNKNOWN, "" }, /* 1320 */
  { "", UNKNOWN, "" }, /* 1321 */
  { "", UNKNOWN, "" }, /* 1322 */
  { "", UNKNOWN, "" }, /* 1323 */
  { "si\'a", UI, "similarly" }, /* 1324 */
  { "si\'e", MOI, "portion selbri" }, /* 1325 */
  { "si\'i", VUhU, "sigma summation" }, /* 1326 */
  { "si\'o", NU, "concept abstract" }, /* 1327 */
  { "si\'u", BAI, "aided by" }, /* 1328 */
  { "", UNKNOWN, "" }, /* 1329 */
  { "so", PA, "9" }, /* 1330 */
  { "", UNKNOWN, "" }, /* 1331 */
  { "", UNKNOWN, "" }, /* 1332 */
  { "soi", SOI, "reciprocal sumti" }, /* 1333 */
  { "", UNKNOWN, "" }, /* 1334 */
  { "", UNKNOWN, "" }, /* 1335 */
  { "", UNKNOWN, "" }, /* 1336 */
  { "", UNKNOWN, "" }, /* 1337 */
  { "so\'a", PA, "almost all" }, /* 1338 */
  { "so\'e", PA, "most" }, /* 1339 */
  { "so\'i", PA, "many" }, /* 1340 */
  { "so\'o", PA, "several" }, /* 1341 */
  { "so\'u", PA, "few" }, /* 1342 */
  { "", UNKNOWN, "" }, /* 1343 */
  { "su", SU, "erase discourse" }, /* 1344 */
  { "", UNKNOWN, "" }, /* 1345 */
  { "", UNKNOWN, "" }, /* 1346 */
  { "", UNKNOWN, "" }, /* 1347 */
  { "", UNKNOWN, "" }, /* 1348 */
  { "", UNKNOWN, "" }, /* 1349 */
  { "", UNKNOWN, "" }, /* 1350 */
  { "", UNKNOWN, "" }, /* 1351 */
  { "su\'a", UI, "I generalize" }, /* 1352 */
  { "su\'e", PA, "at most" }, /* 1353 */
  { "su\'i", VUhU, "plus" }, /* 1354 */
  { "su\'o", PA, "at least" }, /* 1355 */
  { "su\'u", NU, "unspecif abstract" }, /* 1356 */
  { "", UNKNOWN, "" }, /* 1357 */
  { "sy", BY, "s" }, /* 1358 */
  { "", UNKNOWN, "" }, /* 1359 */
  { "", UNKNOWN, "" }, /* 1360 */
  { "", UNKNOWN, "" }, /* 1361 */
  { "", UNKNOWN, "" }, /* 1362 */
  { "", UNKNOWN, "" }, /* 1363 */
  { "", UNKNOWN, "" }, /* 1364 */
  { "", UNKNOWN, "" }, /* 1365 */
  { "", UNKNOWN, "" }, /* 1366 */
  { "", UNKNOWN, "" }, /* 1367 */
  { "", UNKNOWN, "" }, /* 1368 */
  { "", UNKNOWN, "" }, /* 1369 */
  { "", UNKNOWN, "" }, /* 1370 */
  { "", UNKNOWN, "" }, /* 1371 */
  { "", UNKNOWN, "" }, /* 1372 */
  { "", UNKNOWN, "" }, /* 1373 */
  { "", UNKNOWN, "" }, /* 1374 */
  { "", UNKNOWN, "" }, /* 1375 */
  { "", UNKNOWN, "" }, /* 1376 */
  { "", UNKNOWN, "" }, /* 1377 */
  { "", UNKNOWN, "" }, /* 1378 */
  { "", UNKNOWN, "" }, /* 1379 */
  { "", UNKNOWN, "" }, /* 1380 */
  { "", UNKNOWN, "" }, /* 1381 */
  { "", UNKNOWN, "" }, /* 1382 */
  { "", UNKNOWN, "" }, /* 1383 */
  { "", UNKNOWN, "" }, /* 1384 */
  { "", UNKNOWN, "" }, /* 1385 */
  { "ta", KOhA, "that there" }, /* 1386 */
  { "", UNKNOWN, "" }, /* 1387 */
  { "", UNKNOWN, "" }, /* 1388 */
  { "tai", BAI, "in form" }, /* 1389 */
  { "", UNKNOWN, "" }, /* 1390 */
  { "tau", LAU, "shift next lerfu" }, /* 1391 */
  { "", UNKNOWN, "" }, /* 1392 */
  { "", UNKNOWN, "" }, /* 1393 */
  { "ta\'a", COI, "interruption" }, /* 1394 */
  { "ta\'e", TAhE, "habitually" }, /* 1395 */
  { "ta\'i", BAI, "by method" }, /* 1396 */
  { "ta\'o", UI, "by the way" }, /* 1397 */
  { "ta\'u", UI, "making a tanru" }, /* 1398 */
  { "", UNKNOWN, "" }, /* 1399 */
  { "te", SE, "3rd conversion" }, /* 1400 */
  { "", UNKNOWN, "" }, /* 1401 */
  { "", UNKNOWN, "" }, /* 1402 */
  { "tei", TEI, "composite lerfu" }, /* 1403 */
  { "", UNKNOWN, "" }, /* 1404 */
  { "", UNKNOWN, "" }, /* 1405 */
  { "", UNKNOWN, "" }, /* 1406 */
  { "", UNKNOWN, "" }, /* 1407 */
  { "te\'a", VUhU, "to the power" }, /* 1408 */
  { "te\'e", FAhA, "bordering" }, /* 1409 */
  { "", UNKNOWN, "" }, /* 1410 */
  { "te\'o", PA, "exponential e" }, /* 1411 */
  { "te\'u", TEhU, "end mex converters" }, /* 1412 */
  { "", UNKNOWN, "" }, /* 1413 */
  { "ti", KOhA, "this here" }, /* 1414 */
  { "", UNKNOWN, "" }, /* 1415 */
  { "", UNKNOWN, "" }, /* 1416 */
  { "", UNKNOWN, "" }, /* 1417 */
  { "", UNKNOWN, "" }, /* 1418 */
  { "", UNKNOWN, "" }, /* 1419 */
  { "", UNKNOWN, "" }, /* 1420 */
  { "", UNKNOWN, "" }, /* 1421 */
  { "ti\'a", FAhA, "behind" }, /* 1422 */
  { "ti\'e", UI, "I hear" }, /* 1423 */
  { "ti\'i", BAI, "suggested by" }, /* 1424 */
  { "ti\'o", SEI, "mex precedence" }, /* 1425 */
  { "ti\'u", BAI, "associated with time" }, /* 1426 */
  { "", UNKNOWN, "" }, /* 1427 */
  { "to", TO, "start parenthesis" }, /* 1428 */
  { "", UNKNOWN, "" }, /* 1429 */
  { "", UNKNOWN, "" }, /* 1430 */
  { "toi", TOI, "end parenthesis" }, /* 1431 */
  { "", UNKNOWN, "" }, /* 1432 */
  { "", UNKNOWN, "" }, /* 1433 */
  { "", UNKNOWN, "" }, /* 1434 */
  { "", UNKNOWN, "" }, /* 1435 */
  { "to\'a", BY, "lower-case shift" }, /* 1436 */
  { "to\'e", NAhE, "polar opposite" }, /* 1437 */
  { "to\'i", TO, "editorial unquote" }, /* 1438 */
  { "to\'o", FAhA, "away from point" }, /* 1439 */
  { "to\'u", UI, "in brief" }, /* 1440 */
  { "", UNKNOWN, "" }, /* 1441 */
  { "tu", KOhA, "that yonder" }, /* 1442 */
  { "", UNKNOWN, "" }, /* 1443 */
  { "", UNKNOWN, "" }, /* 1444 */
  { "", UNKNOWN, "" }, /* 1445 */
  { "", UNKNOWN, "" }, /* 1446 */
  { "", UNKNOWN, "" }, /* 1447 */
  { "", UNKNOWN, "" }, /* 1448 */
  { "", UNKNOWN, "" }, /* 1449 */
  { "tu\'a", LAhE, "the bridi implied by" }, /* 1450 */
  { "tu\'e", TUhE, "start text scope" }, /* 1451 */
  { "tu\'i", BAI, "associated with site" }, /* 1452 */
  { "tu\'o", PA, "null operand" }, /* 1453 */
  { "tu\'u", TUhU, "end text scope" }, /* 1454 */
  { "", UNKNOWN, "" }, /* 1455 */
  { "ty", BY, "t" }, /* 1456 */
  { "", UNKNOWN, "" }, /* 1457 */
  { "", UNKNOWN, "" }, /* 1458 */
  { "", UNKNOWN, "" }, /* 1459 */
  { "", UNKNOWN, "" }, /* 1460 */
  { "", UNKNOWN, "" }, /* 1461 */
  { "", UNKNOWN, "" }, /* 1462 */
  { "", UNKNOWN, "" }, /* 1463 */
  { "", UNKNOWN, "" }, /* 1464 */
  { "", UNKNOWN, "" }, /* 1465 */
  { "", UNKNOWN, "" }, /* 1466 */
  { "", UNKNOWN, "" }, /* 1467 */
  { "", UNKNOWN, "" }, /* 1468 */
  { "", UNKNOWN, "" }, /* 1469 */
  { "", UNKNOWN, "" }, /* 1470 */
  { "", UNKNOWN, "" }, /* 1471 */
  { "", UNKNOWN, "" }, /* 1472 */
  { "", UNKNOWN, "" }, /* 1473 */
  { "", UNKNOWN, "" }, /* 1474 */
  { "", UNKNOWN, "" }, /* 1475 */
  { "", UNKNOWN, "" }, /* 1476 */
  { "", UNKNOWN, "" }, /* 1477 */
  { "", UNKNOWN, "" }, /* 1478 */
  { "", UNKNOWN, "" }, /* 1479 */
  { "", UNKNOWN, "" }, /* 1480 */
  { "", UNKNOWN, "" }, /* 1481 */
  { "", UNKNOWN, "" }, /* 1482 */
  { "", UNKNOWN, "" }, /* 1483 */
  { "va", VA, "there at" }, /* 1484 */
  { "", UNKNOWN, "" }, /* 1485 */
  { "", UNKNOWN, "" }, /* 1486 */
  { "vai", PA, "hex digit F" }, /* 1487 */
  { "", UNKNOWN, "" }, /* 1488 */
  { "vau", VAU, "end simple bridi" }, /* 1489 */
  { "", UNKNOWN, "" }, /* 1490 */
  { "", UNKNOWN, "" }, /* 1491 */
  { "va\'a", VUhU, "additive inverse" }, /* 1492 */
  { "", UNKNOWN, "" }, /* 1493 */
  { "va\'i", UI, "in other words" }, /* 1494 */
  { "va\'o", BAI, "under conditions" }, /* 1495 */
  { "va\'u", BAI, "benefiting from" }, /* 1496 */
  { "", UNKNOWN, "" }, /* 1497 */
  { "ve", SE, "4th conversion" }, /* 1498 */
  { "", UNKNOWN, "" }, /* 1499 */
  { "", UNKNOWN, "" }, /* 1500 */
  { "vei", VEI, "left bracket" }, /* 1501 */
  { "", UNKNOWN, "" }, /* 1502 */
  { "", UNKNOWN, "" }, /* 1503 */
  { "", UNKNOWN, "" }, /* 1504 */
  { "", UNKNOWN, "" }, /* 1505 */
  { "ve\'a", VEhA, "small space interval" }, /* 1506 */
  { "ve\'e", VEhA, "whole space interval" }, /* 1507 */
  { "ve\'i", VEhA, "tiny space interval" }, /* 1508 */
  { "ve\'o", VEhO, "right bracket" }, /* 1509 */
  { "ve\'u", VEhA, "big space interval" }, /* 1510 */
  { "", UNKNOWN, "" }, /* 1511 */
  { "vi", VA, "here at" }, /* 1512 */
  { "", UNKNOWN, "" }, /* 1513 */
  { "", UNKNOWN, "" }, /* 1514 */
  { "", UNKNOWN, "" }, /* 1515 */
  { "", UNKNOWN, "" }, /* 1516 */
  { "", UNKNOWN, "" }, /* 1517 */
  { "", UNKNOWN, "" }, /* 1518 */
  { "", UNKNOWN, "" }, /* 1519 */
  { "vi\'a", VIhA, "2-space interval" }, /* 1520 */
  { "vi\'e", VIhA, "4-space interval" }, /* 1521 */
  { "vi\'i", VIhA, "1-space interval" }, /* 1522 */
  { "vi\'o", COI, "wilco" }, /* 1523 */
  { "vi\'u", VIhA, "3-space interval" }, /* 1524 */
  { "", UNKNOWN, "" }, /* 1525 */
  { "vo", PA, "4" }, /* 1526 */
  { "", UNKNOWN, "" }, /* 1527 */
  { "", UNKNOWN, "" }, /* 1528 */
  { "voi", NOI, "descriptive clause" }, /* 1529 */
  { "", UNKNOWN, "" }, /* 1530 */
  { "", UNKNOWN, "" }, /* 1531 */
  { "", UNKNOWN, "" }, /* 1532 */
  { "", UNKNOWN, "" }, /* 1533 */
  { "vo\'a", KOhA, "x1 it" }, /* 1534 */
  { "vo\'e", KOhA, "x2 it" }, /* 1535 */
  { "vo\'i", KOhA, "x3 it" }, /* 1536 */
  { "vo\'o", KOhA, "x4 it" }, /* 1537 */
  { "vo\'u", KOhA, "x5 it" }, /* 1538 */
  { "", UNKNOWN, "" }, /* 1539 */
  { "vu", VA, "yonder at" }, /* 1540 */
  { "", UNKNOWN, "" }, /* 1541 */
  { "", UNKNOWN, "" }, /* 1542 */
  { "", UNKNOWN, "" }, /* 1543 */
  { "", UNKNOWN, "" }, /* 1544 */
  { "", UNKNOWN, "" }, /* 1545 */
  { "", UNKNOWN, "" }, /* 1546 */
  { "", UNKNOWN, "" }, /* 1547 */
  { "vu\'a", FAhA, "west of" }, /* 1548 */
  { "vu\'e", UI, "virtue" }, /* 1549 */
  { "vu\'i", LAhE, "the sequence of" }, /* 1550 */
  { "vu\'o", VUhO, "long scope relative" }, /* 1551 */
  { "vu\'u", VUhU, "minus" }, /* 1552 */
  { "", UNKNOWN, "" }, /* 1553 */
  { "vy", BY, "v" }, /* 1554 */
  { "", UNKNOWN, "" }, /* 1555 */
  { "", UNKNOWN, "" }, /* 1556 */
  { "", UNKNOWN, "" }, /* 1557 */
  { "", UNKNOWN, "" }, /* 1558 */
  { "", UNKNOWN, "" }, /* 1559 */
  { "", UNKNOWN, "" }, /* 1560 */
  { "", UNKNOWN, "" }, /* 1561 */
  { "", UNKNOWN, "" }, /* 1562 */
  { "", UNKNOWN, "" }, /* 1563 */
  { "", UNKNOWN, "" }, /* 1564 */
  { "", UNKNOWN, "" }, /* 1565 */
  { "", UNKNOWN, "" }, /* 1566 */
  { "", UNKNOWN, "" }, /* 1567 */
  { "", UNKNOWN, "" }, /* 1568 */
  { "", UNKNOWN, "" }, /* 1569 */
  { "", UNKNOWN, "" }, /* 1570 */
  { "", UNKNOWN, "" }, /* 1571 */
  { "", UNKNOWN, "" }, /* 1572 */
  { "", UNKNOWN, "" }, /* 1573 */
  { "", UNKNOWN, "" }, /* 1574 */
  { "", UNKNOWN, "" }, /* 1575 */
  { "", UNKNOWN, "" }, /* 1576 */
  { "", UNKNOWN, "" }, /* 1577 */
  { "", UNKNOWN, "" }, /* 1578 */
  { "", UNKNOWN, "" }, /* 1579 */
  { "", UNKNOWN, "" }, /* 1580 */
  { "", UNKNOWN, "" }, /* 1581 */
  { "xa", PA, "6" }, /* 1582 */
  { "", UNKNOWN, "" }, /* 1583 */
  { "", UNKNOWN, "" }, /* 1584 */
  { "", UNKNOWN, "" }, /* 1585 */
  { "", UNKNOWN, "" }, /* 1586 */
  { "", UNKNOWN, "" }, /* 1587 */
  { "", UNKNOWN, "" }, /* 1588 */
  { "", UNKNOWN, "" }, /* 1589 */
  { "", UNKNOWN, "" }, /* 1590 */
  { "", UNKNOWN, "" }, /* 1591 */
  { "", UNKNOWN, "" }, /* 1592 */
  { "", UNKNOWN, "" }, /* 1593 */
  { "", UNKNOWN, "" }, /* 1594 */
  { "", UNKNOWN, "" }, /* 1595 */
  { "xe", SE, "5th conversion" }, /* 1596 */
  { "", UNKNOWN, "" }, /* 1597 */
  { "", UNKNOWN, "" }, /* 1598 */
  { "", UNKNOWN, "" }, /* 1599 */
  { "", UNKNOWN, "" }, /* 1600 */
  { "", UNKNOWN, "" }, /* 1601 */
  { "", UNKNOWN, "" }, /* 1602 */
  { "", UNKNOWN, "" }, /* 1603 */
  { "", UNKNOWN, "" }, /* 1604 */
  { "", UNKNOWN, "" }, /* 1605 */
  { "", UNKNOWN, "" }, /* 1606 */
  { "", UNKNOWN, "" }, /* 1607 */
  { "", UNKNOWN, "" }, /* 1608 */
  { "", UNKNOWN, "" }, /* 1609 */
  { "xi", XI, "subscript" }, /* 1610 */
  { "", UNKNOWN, "" }, /* 1611 */
  { "", UNKNOWN, "" }, /* 1612 */
  { "", UNKNOWN, "" }, /* 1613 */
  { "", UNKNOWN, "" }, /* 1614 */
  { "", UNKNOWN, "" }, /* 1615 */
  { "", UNKNOWN, "" }, /* 1616 */
  { "", UNKNOWN, "" }, /* 1617 */
  { "", UNKNOWN, "" }, /* 1618 */
  { "", UNKNOWN, "" }, /* 1619 */
  { "", UNKNOWN, "" }, /* 1620 */
  { "", UNKNOWN, "" }, /* 1621 */
  { "", UNKNOWN, "" }, /* 1622 */
  { "", UNKNOWN, "" }, /* 1623 */
  { "xo", PA, "number ?" }, /* 1624 */
  { "", UNKNOWN, "" }, /* 1625 */
  { "", UNKNOWN, "" }, /* 1626 */
  { "", UNKNOWN, "" }, /* 1627 */
  { "", UNKNOWN, "" }, /* 1628 */
  { "", UNKNOWN, "" }, /* 1629 */
  { "", UNKNOWN, "" }, /* 1630 */
  { "", UNKNOWN, "" }, /* 1631 */
  { "", UNKNOWN, "" }, /* 1632 */
  { "", UNKNOWN, "" }, /* 1633 */
  { "", UNKNOWN, "" }, /* 1634 */
  { "", UNKNOWN, "" }, /* 1635 */
  { "", UNKNOWN, "" }, /* 1636 */
  { "", UNKNOWN, "" }, /* 1637 */
  { "xu", UI, "true-false ?" }, /* 1638 */
  { "", UNKNOWN, "" }, /* 1639 */
  { "", UNKNOWN, "" }, /* 1640 */
  { "", UNKNOWN, "" }, /* 1641 */
  { "", UNKNOWN, "" }, /* 1642 */
  { "", UNKNOWN, "" }, /* 1643 */
  { "", UNKNOWN, "" }, /* 1644 */
  { "", UNKNOWN, "" }, /* 1645 */
  { "", UNKNOWN, "" }, /* 1646 */
  { "", UNKNOWN, "" }, /* 1647 */
  { "", UNKNOWN, "" }, /* 1648 */
  { "", UNKNOWN, "" }, /* 1649 */
  { "", UNKNOWN, "" }, /* 1650 */
  { "", UNKNOWN, "" }, /* 1651 */
  { "xy", BY, "x" }, /* 1652 */
  { "", UNKNOWN, "" }, /* 1653 */
  { "", UNKNOWN, "" }, /* 1654 */
  { "", UNKNOWN, "" }, /* 1655 */
  { "", UNKNOWN, "" }, /* 1656 */
  { "", UNKNOWN, "" }, /* 1657 */
  { "", UNKNOWN, "" }, /* 1658 */
  { "", UNKNOWN, "" }, /* 1659 */
  { "", UNKNOWN, "" }, /* 1660 */
  { "", UNKNOWN, "" }, /* 1661 */
  { "", UNKNOWN, "" }, /* 1662 */
  { "", UNKNOWN, "" }, /* 1663 */
  { "", UNKNOWN, "" }, /* 1664 */
  { "", UNKNOWN, "" }, /* 1665 */
  { "", UNKNOWN, "" }, /* 1666 */
  { "", UNKNOWN, "" }, /* 1667 */
  { "", UNKNOWN, "" }, /* 1668 */
  { "", UNKNOWN, "" }, /* 1669 */
  { "", UNKNOWN, "" }, /* 1670 */
  { "", UNKNOWN, "" }, /* 1671 */
  { "", UNKNOWN, "" }, /* 1672 */
  { "", UNKNOWN, "" }, /* 1673 */
  { "", UNKNOWN, "" }, /* 1674 */
  { "", UNKNOWN, "" }, /* 1675 */
  { "", UNKNOWN, "" }, /* 1676 */
  { "", UNKNOWN, "" }, /* 1677 */
  { "", UNKNOWN, "" }, /* 1678 */
  { "", UNKNOWN, "" }, /* 1679 */
  { "za", ZI, "medium time" }, /* 1680 */
  { "", UNKNOWN, "" }, /* 1681 */
  { "", UNKNOWN, "" }, /* 1682 */
  { "zai", LAU, "select alphabet" }, /* 1683 */
  { "", UNKNOWN, "" }, /* 1684 */
  { "zau", BAI, "approved by" }, /* 1685 */
  { "", UNKNOWN, "" }, /* 1686 */
  { "", UNKNOWN, "" }, /* 1687 */
  { "za\'a", UI, "I observe" }, /* 1688 */
  { "za\'e", BAhE, "nonce-word next" }, /* 1689 */
  { "za\'i", NU, "state abstract" }, /* 1690 */
  { "za\'o", ZAhO, "superfective" }, /* 1691 */
  { "za\'u", PA, "greater than" }, /* 1692 */
  { "", UNKNOWN, "" }, /* 1693 */
  { "ze", PA, "7" }, /* 1694 */
  { "", UNKNOWN, "" }, /* 1695 */
  { "", UNKNOWN, "" }, /* 1696 */
  { "zei", ZEI, "lujvo glue" }, /* 1697 */
  { "", UNKNOWN, "" }, /* 1698 */
  { "", UNKNOWN, "" }, /* 1699 */
  { "", UNKNOWN, "" }, /* 1700 */
  { "", UNKNOWN, "" }, /* 1701 */
  { "ze\'a", ZEhA, "medium time interval" }, /* 1702 */
  { "ze\'e", ZEhA, "whole time interval" }, /* 1703 */
  { "ze\'i", ZEhA, "short time interval" }, /* 1704 */
  { "ze\'o", FAhA, "outward" }, /* 1705 */
  { "ze\'u", ZEhA, "long time interval" }, /* 1706 */
  { "", UNKNOWN, "" }, /* 1707 */
  { "zi", ZI, "short time" }, /* 1708 */
  { "", UNKNOWN, "" }, /* 1709 */
  { "", UNKNOWN, "" }, /* 1710 */
  { "", UNKNOWN, "" }, /* 1711 */
  { "", UNKNOWN, "" }, /* 1712 */
  { "", UNKNOWN, "" }, /* 1713 */
  { "", UNKNOWN, "" }, /* 1714 */
  { "", UNKNOWN, "" }, /* 1715 */
  { "", UNKNOWN, "" }, /* 1716 */
  { "zi\'e", ZIhE, "rel clause joiner" }, /* 1717 */
  { "", UNKNOWN, "" }, /* 1718 */
  { "zi\'o", KOhA, "nonexistent it" }, /* 1719 */
  { "", UNKNOWN, "" }, /* 1720 */
  { "", UNKNOWN, "" }, /* 1721 */
  { "zo", ZO, "1-word quote" }, /* 1722 */
  { "", UNKNOWN, "" }, /* 1723 */
  { "", UNKNOWN, "" }, /* 1724 */
  { "zoi", ZOI, "non-Lojban quote" }, /* 1725 */
  { "", UNKNOWN, "" }, /* 1726 */
  { "", UNKNOWN, "" }, /* 1727 */
  { "", UNKNOWN, "" }, /* 1728 */
  { "", UNKNOWN, "" }, /* 1729 */
  { "zo\'a", FAhA, "tangential to" }, /* 1730 */
  { "zo\'e", KOhA, "unspecif it" }, /* 1731 */
  { "zo\'i", FAhA, "inward" }, /* 1732 */
  { "zo\'o", UI, "humorously" }, /* 1733 */
  { "zo\'u", ZOhU, "end prenex" }, /* 1734 */
  { "", UNKNOWN, "" }, /* 1735 */
  { "zu", ZI, "long time" }, /* 1736 */
  { "", UNKNOWN, "" }, /* 1737 */
  { "", UNKNOWN, "" }, /* 1738 */
  { "", UNKNOWN, "" }, /* 1739 */
  { "", UNKNOWN, "" }, /* 1740 */
  { "", UNKNOWN, "" }, /* 1741 */
  { "", UNKNOWN, "" }, /* 1742 */
  { "", UNKNOWN, "" }, /* 1743 */
  { "zu\'a", FAhA, "on the left of" }, /* 1744 */
  { "zu\'e", BAI, "with actor" }, /* 1745 */
  { "zu\'i", KOhA, "typical it" }, /* 1746 */
  { "zu\'o", NU, "activity abstract" }, /* 1747 */
  { "zu\'u", UI, "on the one hand" }, /* 1748 */
  { "", UNKNOWN, "" }, /* 1749 */
  { "zy", BY, "z" } /* 1750 */
};
