.TH "jbofihe" 1L "April 2000"
.SH NAME
jbofihe \- Lojban parser / grammar checker / word glosser
.SH SYNOPSIS
.B jbofihe
[-v] [ -h | --help | -? ] [ -k ] [ -g ] [ -t ] [-tf ] [ -l ] [ -b ] [ -x ] [ -H ] [ -m ] [ -w width ] [-ie] [-re] [filename]
.SH DESCRIPTION
.I jbofihe
is a program that reads a piece of Lojban text and checks it for
grammatical correctness.  If it passes, the output will show the
nesting of the major grammatical constructs by means of bracketing.
Also, words will have their approximate English translations shown.
Some of these translations are context-dependent.
.SH OPTIONS
.TP
.B -v
Show the program version and exit.
.TP
.B -h
Show help page
.TP
.B --help
Show help page
.TP
.B -?
Show help page
.TP
.B -k
Display lists of tokens after parse and after pseudo-token insertion
(mainly useful for debugging the lexer and parser).
.TP
.B -g
Produce a rough English gloss (superseded)
.TP
.B -t
Produce a syntax tree on stdout.  Nodes with only one child will be
filtered out.
.TP
.B -tf
Produce a full syntax tree on stdout, including nodes with only one
child.
.TP
.B -l
Produce output for typesetting with LaTeX.
.TP
.B -x
Produce plain text output.
.TP
.B  -w width
Set the width of the screen (in characters) for the -x option.
.TP
.B -H
Produce HTML output
.TP
.B -b
Produce output in 'block' mode, where each block shows the Lojban, the
English gloss and a term tag where applicable. The default is
'running' mode, with term tags, Lojban and the English gloss all on
the same line.  Only applicable to -l and -x (not to -h).
.TP
.B -m
Show the amount of memory used by the processing.
.TP
.B -ie
Display elided separators and terminators in the output.
.TP
.B -re
Require the input text to have all elidable cmavo actually present.  (May be
useful for forcing the user to think about the grammatical structure of the
input text more carefully when debugging parse errors.)
.TP
.B filename
The name of the file containing text to be parsed.  If omitted, the text is
read from standard input.
.SH SEE ALSO
.PP
.TP
.B cmafihe
A program which does English word glossing without the grammar
parsing and checking stage.  This is useful to get words quickly
looked up when studying someone else's text which contains many
grammatical errors.
.TP
.B smujajgau
A program for compiling binary dictionaries for use by jbofihe
.SH FILES
.TP
.B /usr/local/lib/jbofihe/smujmaji.dat
This file contains all the dictionary data compiled (using
.I smujajgau
) into a binary format to facilitate lookup and search.
.TP
.B /usr/local/bin/jbofihe
The executable.
.SH ENVIRONMENT
.TP
.B JBOFIHE_DICTIONARY
This should point to the name of the file containing the dictionary.
The default is /usr/local/lib/jbofihe/smujmaji.dat
\".SH CAVEATS
.SH BUGS
ju'oru'e so'imei (Surely there are many).
.SH REFERENCES
.TP
.B http://go.to/jbofihe
Home page for the jbofihe project
.TP
.B http://www.rrbcurnow.freeuk.com/lojban/
My Lojban page.
.TP
.B http://www.lojban.org/
Home page of the Lojban community
.SH AUTHOR
Richard Curnow
.B <rpc@myself.com>
