#!/usr/bin/env perl

# Primitive method for running some regression tests

use strict;

$ENV{"JBOFIHE_DICTIONARY"} = "/home/richard/cvswork/jbofihe/smujmaji.dat";

if (!-r "PROGRAM") {
    die "No PROGRAM file to define the program!";
}

open (IN, "<PROGRAM");
my $line = <IN>;
close (IN);
chomp $line;

my $cmd = $line;

my @inputs = @ARGV;
for my $in (@inputs) {
    $in =~ s/\.in$//;
    $in .= ".in";
    my $a = $in;
    $a =~ s/\.in$/\.arg/;
    my @args = ();
    if (-r $a) {
	open (A, "<".$a);
	@args = (<A>);
	close (A);
	foreach (@args) {
	    chomp;
	    s/^ +//;
	    s/ +$//;
	}
    }
    my $base = $in;
    $base =~ s/\.in$//;
    my $pid = fork;
    unless ($pid) {
	# child
	open (STDIN, "<$in");
	open (STDOUT, ">$base.out");
	open (STDERR, ">$base.err");
	exec $cmd, @args;
	die "Could not exec program";
    }
    wait; # only in the parent
    my $status = $?;
    my $core = (($status & 128) != 0);
    my $signal = ($status & 127);
    my $exit = ($status >> 8);

# Check exit status
    open (OUT, ">$base.exi");
    print OUT $status."\n";
    close (OUT);
}

